import { expect, test } from "@playwright/test";

const origin = process.env.PREVIEW_URL ?? "http://localhost:3002";
test("hosted workspace works without an operational API and survives refresh", async ({ page, browser }) => {
  const errors: string[] = [];
  const requests: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => {
    if (["fetch", "xhr"].includes(request.resourceType()) && !request.url().includes("__next")) requests.push(request.url());
  });
  await page.goto(origin);
  await expect(page.getByText("Browser demo.")).toHaveCount(0);
  await expect(page.getByText("Local demonstrator.")).toHaveCount(0);
  await expect(page.getByText("Fixture mode")).toHaveCount(0);
  await expect(page.locator(".workspace-chip")).toContainText("Wallaroo Media");
  await expect(page.getByRole("tab", { name: "Overview" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Technical SEO Monitor" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "LinkedIn Outreach Assistant" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Partner Development" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Outbound Email SDR" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "RFP Opportunity Scout" })).toBeVisible();
  await expect(page.getByRole("heading", { name: /The team ran overnight/ })).toBeVisible();
  await expect(page.getByRole("region", { name: "Team activity" })).toBeVisible();
  await expect(page.getByRole("region", { name: "Specialist status" })).toBeVisible();
  await expect(page.getByRole("region", { name: "Specialist status" }).getByText("Completed overnight").first()).toBeVisible();
  await expect(page.getByRole("region", { name: "Specialist status" }).getByText("On pass")).toBeVisible();
  await expect(page.getByRole("region", { name: "Team activity" }).getByText("Held for review")).toHaveCount(0);
  await page.getByRole("tab", { name: "Technical SEO Monitor" }).click();
  await expect(page.getByRole("region", { name: "Technical SEO Monitor dashboard" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Prepare first draft" })).toHaveCount(0);
  await expect(page.getByRole("region", { name: "Technical SEO Monitor run log" })).toBeVisible();
  await expect(page.locator(".studio-output-content")).toContainText("wallaroomedia.com");
  await page.getByRole("tab", { name: "LinkedIn Outreach Assistant" }).click();
  await expect(page.getByRole("region", { name: "LinkedIn Outreach Assistant dashboard" })).toBeVisible();
  await expect(page.locator(".studio-output-content")).toContainText("Called to Surf");
  await expect(page.getByText("This capability is not implemented yet.")).toHaveCount(0);
  await page.getByRole("tab", { name: "Outbound Email SDR" }).click();
  await expect(page.getByRole("region", { name: "Outbound Email SDR dashboard" })).toContainText("This specialist writes completed work into the log");
  await expect(page.locator(".studio-output-content")).toContainText("Book 30 minutes");
  await page.getByRole("button", { name: "Company sources" }).click();
  await expect(page.getByRole("heading", { name: "Connections", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Wallaroo Media · LinkedIn" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Wallaroo Media · Klaviyo" })).toBeVisible();
  await page.goto(`${origin}/?view=today`);
  await expect(page.getByRole("heading", { name: /The team ran overnight/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /Human replies/ })).toBeVisible();
  await page.goto(`${origin}/?view=opportunities`);
  await page.getByRole("row").filter({ hasText: "Called to Surf" }).getByRole("button", { name: "Open", exact: true }).click();
  const record = page.getByRole("dialog");
  await expect(record.getByRole("region", { name: "Workspace conversation log" })).toBeVisible();
  await expect(record.getByText(/Who on your side owns paid/)).toBeVisible();
  await expect(record.getByText("Book 30 minutes with a senior strategist").first()).toBeVisible();
  await expect(record.getByText("Connection accepted").first()).toBeVisible();
  await expect(record.getByRole("button", { name: "Take over conversation" })).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=opportunities`);
  await page.getByRole("row").filter({ hasText: "Kaja Beauty" }).getByRole("button", { name: "Open", exact: true }).click();
  await expect(page.getByRole("dialog").locator(".conversation-channel", { hasText: "LinkedIn" }).first()).toBeVisible();
  await expect(page.getByRole("dialog").getByText("Connection accepted").first()).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=opportunities`);
  await page.getByRole("row").filter({ hasText: "Stately" }).getByRole("button", { name: "Open", exact: true }).click();
  await expect(page.getByRole("dialog").locator(".conversation-channel", { hasText: "Website" }).first()).toBeVisible();
  await expect(page.getByRole("dialog").getByText(/Do you run Klaviyo/)).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=decisions`);
  await expect(page.getByRole("heading", { name: /Approved overnight/ })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve initiative" })).toHaveCount(0);
  await expect(page.getByText("What happened because they were approved")).toBeVisible();
  await page.goto(`${origin}/?view=scenarios`);
  await expect(page.getByText("Unavailable")).toHaveCount(0);
  await expect(page.getByText("Unknown", { exact: true })).toHaveCount(0);
  await expect(page.getByText(/Incremental ROI:/).first()).toContainText("%");
  await expect(page.getByText(/Same 30 days with specialists idle overnight/)).toBeVisible();
  await page.goto(`${origin}/?view=journey`);
  await expect(page.getByText("How DAVID moved")).toBeVisible();
  await expect(page.getByText("No evidence", { exact: true })).toHaveCount(0);
  await expect(page.getByText("Connection accepted").first()).toBeVisible();
  await expect(page.getByText("Meeting booked").first()).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=today`);
  await page.getByRole("tab", { name: "Technical SEO Monitor" }).click();
  await page.getByRole("button", { name: "Access, limits & history" }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("button", { name: "Run bounded preparation" }).click();
  await expect(dialog.locator(".prose").first()).toContainText("wallaroomedia.com");
  await dialog.getByRole("button", { name: "Rules & limits" }).click();
  await dialog.getByRole("button", { name: "Pause workspace", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Workspace paused", exact: true })).toBeDisabled();
  await page.reload();
  await expect(page.getByRole("main").getByRole("heading", { level: 1 })).toBeVisible();
  await page.getByRole("button", { name: "Access, limits & history" }).click();
  await dialog.getByRole("button", { name: "Rules & limits" }).click();
  await expect(dialog.getByRole("button", { name: "Workspace paused", exact: true })).toBeDisabled();
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 390, height: 844 });
  for (const view of ["today", "team", "activation", "opportunities", "decisions", "journey", "scenarios", "connections", "operator"]) {
    await page.goto(`${origin}/?view=${view}`);
    await expect(page.getByRole("main").getByRole("heading", { level: 1 })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), view).toBe(false);
  }
  const other = await browser.newContext();
  const otherPage = await other.newPage();
  await otherPage.goto(origin);
  await otherPage.getByRole("tab", { name: "Technical SEO Monitor" }).click();
  await otherPage.getByRole("button", { name: "Access, limits & history" }).click();
  await otherPage.getByRole("dialog").getByRole("button", { name: "Rules & limits" }).click();
  await expect(otherPage.getByRole("dialog").getByRole("button", { name: "Pause workspace", exact: true })).toBeEnabled();
  await other.close();
  expect((await page.request.get(`${origin}/api/state`)).status()).toBe(404);
  expect((await page.request.post(`${origin}/api/command`, { data: { type: "reset" } })).status()).toBeGreaterThanOrEqual(400);
  expect(errors).toEqual([]);
  expect(requests).toEqual([]);
});
