import { expect, test } from "@playwright/test";

const origin = process.env.PREVIEW_URL ?? "http://localhost:3002";
test("hosted workspace works without an operational API and survives refresh", async ({ page, browser }) => {
  const errors: string[] = [];
  const requests: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => {
    if (["fetch", "xhr"].includes(request.resourceType()) && !request.url().includes("__next")) requests.push(request.url());
  });
  await page.goto(origin);
  await expect(page.getByText("Browser demo.", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Overnight recap", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Results", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Activity", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Open Account Intelligence recap" }).first().click();
  await expect(page.getByRole("region", { name: "Account Intelligence recap" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Prepare first draft" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Access, limits & history" })).toHaveCount(0);
  await page.getByRole("button", { name: "All specialists" }).click();
  await page.getByRole("button", { name: "Open Technical SEO recap" }).first().click();
  await expect(page.getByRole("region", { name: "Technical SEO recap" })).toBeVisible();
  await expect(page.getByText(/does not create trackable leads/i)).toBeVisible();
  await expect(page.getByRole("region", { name: "Technical SEO recap" })).toContainText("Pages crawled");
  await expect(page.getByRole("region", { name: "Technical SEO recap" })).toContainText("Rank rows");
  await page.getByRole("button", { name: "All specialists" }).click();
  await page.getByRole("button", { name: /New leads/ }).click();
  await expect(page.getByRole("heading", { name: "Pipeline", exact: true })).toBeVisible();
  await page.goto(`${origin}/?view=team&agent=technical-seo-monitor`);
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("heading", { name: "Technical SEO", exact: true })).toBeVisible();
  await expect(dialog.getByRole("button", { name: "Start DataForSEO crawl" })).toBeVisible();
  await expect(dialog.locator(".prose").first()).toContainText("ILLUSTRATIVE FIXTURE");
  await dialog.getByLabel("Keywords (one per line, max 20)").fill("managed seo\nshopify seo");
  await dialog.getByRole("button", { name: "Save keywords and location" }).click();
  await dialog.getByRole("button", { name: "Start DataForSEO crawl" }).click();
  await expect(dialog.getByText(/FIXTURE_ONLY_dataforseo_|fixture task|pages/i).first()).toBeVisible();
  await dialog.getByRole("button", { name: "Rules & limits" }).click();
  await dialog.getByRole("button", { name: "Pause workspace", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Workspace paused", exact: true })).toBeDisabled();
  await page.reload();
  await expect(dialog.getByRole("heading", { name: "Technical SEO", exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Rules & limits" }).click();
  await expect(dialog.getByRole("button", { name: "Workspace paused", exact: true })).toBeDisabled();
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 390, height: 844 });
  for (const view of ["today", "team", "activation", "opportunities", "decisions", "journey", "scenarios", "connections", "operator"]) {
    await page.goto(`${origin}/?view=${view}`);
    await expect(page.getByRole("main").getByRole("heading", { level: 1 })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), view).toBe(false);
  }
  const other = await browser.newContext();
  const otherPage = await other.newPage();
  await otherPage.goto(origin);
  await otherPage.getByRole("link", { name: "AI Agents", exact: true }).click();
  await otherPage.getByRole("button", { name: "Workspace limits" }).click();
  await otherPage.getByRole("dialog").getByRole("button", { name: "Rules & limits" }).click();
  await expect(otherPage.getByRole("dialog").getByRole("button", { name: "Pause workspace", exact: true })).toBeEnabled();
  await other.close();
  expect((await page.request.get(`${origin}/api/state`)).status()).toBe(404);
  expect((await page.request.post(`${origin}/api/command`, { data: { type: "reset" } })).status()).toBeGreaterThanOrEqual(400);
  expect(errors).toEqual([]);
  expect(requests).toEqual([]);
});
