import { expect, test } from "@playwright/test";

const origin = process.env.PREVIEW_URL ?? "http://localhost:3002";
test("hosted workspace works without an operational API and survives refresh", async ({ page, browser }) => {
  const errors: string[] = [];
  const requests: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("request", request => {
    if (["fetch", "xhr"].includes(request.resourceType()) && !request.url().includes("__next")) requests.push(request.url());
  });
  await page.goto(origin);
  await expect(page.getByText("Browser demo.")).toHaveCount(0);
  await expect(page.getByText("Local demonstrator.")).toHaveCount(0);
  await expect(page.getByText("Fixture mode")).toHaveCount(0);
  await expect(page.locator(".workspace-chip")).toContainText("Wallaroo Media");
  await expect(page.getByRole("heading", { name: "Overnight recap", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Website Sales Concierge recap" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Technical SEO recap" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Open LinkedIn Outreach Assistant recap" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Partner Development recap" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Open Outbound Email SDR recap" }).first()).toBeVisible();
  await expect(page.getByRole("button", { name: "Open RFP Opportunity Scout recap" }).first()).toBeVisible();
  await expect(page.getByRole("heading", { name: /The team ran overnight/ })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Activity", exact: true })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "Results", exact: true })).toBeVisible();
  await expect(page.getByText("Completed overnight").first()).toBeVisible();
  await expect(page.getByText("On pass").first()).toBeVisible();
  await page.getByRole("button", { name: "Open Technical SEO recap" }).first().click();
  await expect(page.getByRole("region", { name: "Technical SEO recap" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Prepare first draft" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Open this run" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Access, limits & history" })).toHaveCount(0);
  await expect(page.getByText(/does not create trackable leads/i)).toBeVisible();
  await expect(page.getByRole("region", { name: "Technical SEO recap" })).toContainText("Pages crawled");
  await expect(page.getByRole("region", { name: "Technical SEO recap" })).toContainText("Rank rows");
  await expect(page.getByLabel("Technical SEO overnight from 3:00 AM to 3:00 AM")).toContainText("Title and description fixes");
  await page.getByRole("button", { name: "All specialists" }).click();
  await page.getByRole("button", { name: "Open LinkedIn Outreach Assistant recap" }).first().click();
  await expect(page.getByRole("region", { name: "LinkedIn Outreach Assistant recap" })).toBeVisible();
  await expect(page.getByRole("button", { name: "See the conversation" })).toBeVisible();
  await page.getByRole("button", { name: "All specialists" }).click();
  await page.getByRole("button", { name: "Open Outbound Email SDR recap" }).first().click();
  await expect(page.getByRole("region", { name: "Outbound Email SDR recap" })).toBeVisible();
  await expect(page.getByRole("button", { name: "See the conversation" })).toBeVisible();
  await expect(page.getByText("3:00 AM to 3:00 AM").first()).toBeVisible();
  await page.getByRole("button", { name: "All specialists" }).click();
  await page.getByRole("button", { name: "Open Website Sales Concierge recap" }).first().click();
  await page.getByRole("button", { name: "Watch this conversation" }).click();
  await expect(page.getByRole("dialog").locator(".conversation-channel", { hasText: "Website" }).first()).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=today`);
  await expect(page.getByRole("heading", { name: /The team ran overnight/ })).toBeVisible();
  await expect(page.getByRole("button", { name: /Meetings booked/ })).toBeVisible();
  await page.getByRole("button", { name: /Meetings booked/ }).click();
  await expect(page.getByRole("heading", { name: "Pipeline", exact: true })).toBeVisible();
  await page.goto(`${origin}/?view=opportunities`);
  await page.getByRole("row").filter({ hasText: "Called to Surf" }).getByRole("button", { name: "Open", exact: true }).click();
  const record = page.getByRole("dialog");
  await expect(record.getByRole("region", { name: "Workspace conversation log" })).toBeVisible();
  await expect(record.getByText(/Who on your side owns paid/)).toBeVisible();
  await expect(record.getByText("Book 30 minutes with a senior strategist").first()).toBeVisible();
  await expect(record.getByText("Connection accepted").first()).toBeVisible();
  await expect(record.getByRole("button", { name: "Take over conversation" })).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=opportunities`);
  await page.getByRole("row").filter({ hasText: "Kaja Beauty" }).getByRole("button", { name: "Open", exact: true }).click();
  await expect(page.getByRole("dialog").locator(".conversation-channel", { hasText: "LinkedIn" }).first()).toBeVisible();
  await expect(page.getByRole("dialog").getByText("Connection accepted").first()).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=opportunities`);
  await page.getByRole("row").filter({ hasText: "Stately" }).getByRole("button", { name: "Open", exact: true }).click();
  await expect(page.getByRole("dialog").locator(".conversation-channel", { hasText: "Website" }).first()).toBeVisible();
  await expect(page.getByRole("dialog").getByText(/Do you run Klaviyo/)).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=decisions`);
  await expect(page.getByRole("heading", { name: /Approved overnight/ })).toBeVisible();
  await expect(page.getByRole("button", { name: "Approve initiative" })).toHaveCount(0);
  await expect(page.getByText("What happened because they were approved")).toBeVisible();
  await page.goto(`${origin}/?view=scenarios`);
  await expect(page.getByText("Unavailable")).toHaveCount(0);
  await expect(page.getByText("Unknown", { exact: true })).toHaveCount(0);
  await expect(page.getByText(/Incremental ROI:/).first()).toContainText("%");
  await expect(page.getByText(/Same 30 days with specialists idle overnight/)).toBeVisible();
  await page.goto(`${origin}/?view=journey`);
  await expect(page.getByText("How DAVID moved")).toBeVisible();
  await expect(page.getByText("No evidence", { exact: true })).toHaveCount(0);
  await expect(page.getByText("Connection accepted").first()).toBeVisible();
  await expect(page.getByText("Meeting booked").first()).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto(`${origin}/?view=team&agent=technical-seo-monitor`);
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("heading", { name: "Technical SEO", exact: true })).toBeVisible();
  await expect(dialog.getByRole("button", { name: "Start DataForSEO crawl" })).toBeVisible();
  await expect(dialog.getByText(/ILLUSTRATIVE FIXTURE/).first()).toBeVisible();
  await expect(dialog.getByText("wallaroomedia.com").first()).toBeVisible();
  await dialog.getByRole("button", { name: "Start DataForSEO crawl" }).click();
  await expect(dialog.getByText(/FIXTURE_ONLY_dataforseo_|fixture task|pages/i).first()).toBeVisible();
  await dialog.getByRole("button", { name: "Rules & limits" }).click();
  await dialog.getByRole("button", { name: "Pause workspace", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Workspace paused", exact: true })).toBeDisabled();
  await page.reload();
  await expect(dialog.getByRole("heading", { name: "Technical SEO", exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Rules & limits" }).click();
  await expect(dialog.getByRole("button", { name: "Workspace paused", exact: true })).toBeDisabled();
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 390, height: 844 });
  for (const view of ["today", "team", "activation", "opportunities", "decisions", "journey", "scenarios", "connections", "operator"]) {
    await page.goto(`${origin}/?view=${view}`);
    await expect(page.getByRole("main").getByRole("heading", { level: 1 })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), view).toBe(false);
  }
  const other = await browser.newContext();
  const otherPage = await other.newPage();
  await otherPage.goto(origin);
  await otherPage.getByRole("link", { name: "AI Agents", exact: true }).click();
  await otherPage.getByRole("button", { name: "Workspace limits" }).click();
  await otherPage.getByRole("dialog").getByRole("button", { name: "Rules & limits" }).click();
  await expect(otherPage.getByRole("dialog").getByRole("button", { name: "Pause workspace", exact: true })).toBeEnabled();
  await other.close();
  expect((await page.request.get(`${origin}/api/state`)).status()).toBe(404);
  expect((await page.request.post(`${origin}/api/command`, { data: { type: "reset" } })).status()).toBeGreaterThanOrEqual(400);
  expect(errors).toEqual([]);
  expect(requests).toEqual([]);
});
