import {test,expect} from '@playwright/test';
const origin=process.env.PREVIEW_URL??'http://localhost:3002';
test('guided setup drafts cited answers, reviews mappings, preserves decisions and resumes',async({page},testInfo)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const apiCalls:string[]=[];page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))apiCalls.push(r.url());});
 await page.goto(`${origin}/?view=activation`);
 await expect(page.getByRole('heading',{name:'Your website is a starting point.'})).toBeVisible();
 await page.getByRole('button',{name:'Try with a sample company'}).click();
 await expect(page.getByLabel('Review company name',{exact:true})).toHaveValue('Example Advisory');
 await expect(page.getByLabel('Review offers',{exact:true})).toHaveValue(/revenue operations consulting/);
 await expect(page.getByRole('button',{name:'Confirm company profile'})).toBeDisabled();
 await page.getByLabel('I reviewed the sources and corrected these company facts.').check();
 await page.getByRole('button',{name:'Confirm company profile'}).click();
 await page.getByRole('radio',{name:/Create qualified demand/}).check();
 await page.getByRole('button',{name:'Use this objective and team'}).click();
 await page.getByRole('button',{name:'Load sample spreadsheet headers'}).click();
 await expect(page.getByText(/17 of 17 required fields matched/)).toBeVisible();
 await page.getByLabel('I reviewed this resource, owner and mapping and authorize its bounded read check.').check();
 await page.getByRole('button',{name:'Use this source and check access'}).click();
 await expect(page.getByText(/Sample source selection saved/)).toBeVisible();
 await page.getByRole('button',{name:'Continue to permissions'}).click();
 await expect(page.getByLabel(/Daily AI budget/)).toHaveValue('');
 await page.getByLabel('Approver email',{exact:true}).fill('owner@example.invalid');
 await page.getByLabel('Escalation owner email',{exact:true}).fill('operator@example.invalid');
 await page.getByLabel(/Daily AI budget/).fill('500');
 await page.getByLabel('Daily capacity per agent',{exact:true}).fill('2');
 await page.getByLabel('Authoritative outcome sources',{exact:true}).fill('CRM owned by the sales lead; payments unavailable');
 await page.getByLabel('I approve these operating limits, responsibilities and the displayed approval policy.').check();
 await page.getByRole('button',{name:'Save reviewed permissions'}).click();
 await page.getByRole('button',{name:'Apply reviewed settings',exact:true}).click();
 await page.getByRole('button',{name:'Resume after readiness checks',exact:true}).click();
 await page.getByRole('button',{name:'Prepare with Account Intelligence',exact:true}).click();
 await page.getByText(/Company positioning profile · draft/).click();
 await expect(page.locator('.onboarding-template').first()).toContainText('Example Advisory');
 await page.getByRole('button',{name:'Review and accept this output',exact:true}).click();
 await expect(page.getByText(/Company positioning profile · reviewed/)).toBeVisible();
 await page.reload();await expect(page.getByRole('heading',{name:'Review your first useful work.'})).toBeVisible();
 await page.locator('nav[aria-label="Guided setup stages"] button').first().click();
 await expect(page.getByLabel('Review company name',{exact:true})).toHaveValue('Example Advisory');
 await page.screenshot({path:testInfo.outputPath('guided-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 for(let i=0;i<5;i++){await page.locator('nav[aria-label="Guided setup stages"] button').nth(i).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),`stage ${i}`).toBe(false);}
 await page.locator('nav[aria-label="Guided setup stages"] button').first().click();await page.screenshot({path:testInfo.outputPath('guided-mobile.png'),fullPage:true});
 await page.goto(`${origin}/?view=activation&workspace=northstar`);await expect(page.getByRole('button',{name:'Try with a sample company'})).toBeVisible();await expect(page.getByLabel('Review company name',{exact:true})).toHaveCount(0);
 expect(errors).toEqual([]);expect(apiCalls).toEqual([]);
});
