import { expect, test } from '@playwright/test';

const origin=process.env.PREVIEW_URL??'http://localhost:3002';
test('onboarding collects reusable answers, resumes, isolates workspaces and exposes honest readiness',async({page},testInfo)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${origin}/?view=activation&mode=profile`);
 await page.getByLabel('Company name',{exact:true}).fill('Example Advisory');
 await page.getByLabel('Company website',{exact:true}).fill('https://example.invalid');
 await page.getByLabel('Offers',{exact:true}).fill('Advisory\nImplementation');
 await page.getByLabel('Customers you serve').fill('B2B service businesses');
 await page.getByLabel('Business priorities').fill('Recover proposals');
 await page.getByLabel('What would success look like?').fill('Qualified replies and verified bookings');
 await page.getByRole('button',{name:'Save setup',exact:true}).click();
 await expect(page.getByText(/Saved revision 1/)).toBeVisible();
 await page.getByRole('button',{name:/2\. Team & responsibilities/}).click();
 await page.getByLabel('Account Intelligence',{exact:true}).check();
 await page.getByRole('button',{name:/3\. Systems & sources/}).click();
 await page.getByRole('button',{name:'Add a system',exact:true}).click();
 await page.getByLabel('System 1 purpose',{exact:true}).selectOption('website');
 await page.getByLabel('System 1 tool',{exact:true}).fill('Company website');
 await page.getByLabel('System 1 owner',{exact:true}).fill('Company owner');
 await page.getByLabel('System 1 selected resource',{exact:true}).fill('https://example.invalid');
 await page.getByRole('button',{name:/4\. Operating permissions/}).click();
 await page.getByLabel('Escalation operator email').fill('operator@example.invalid');
 await page.getByLabel(/Daily AI budget/).fill('500');
 await page.getByLabel('Daily action / per-agent preparation capacity',{exact:true}).fill('2');
 await page.getByLabel(/I reviewed these operating limits/).check();
 await page.getByRole('button',{name:/5\. People & measurement/}).click();
 await page.getByRole('button',{name:'Add a person',exact:true}).click();
 await page.getByLabel('Person 1 name',{exact:true}).fill('Example Owner');
 await page.getByLabel('Person 1 email',{exact:true}).fill('owner@example.invalid');
 await page.getByLabel('Person 1 access',{exact:true}).selectOption('workspace_owner');
 await page.getByLabel('Measurement owner',{exact:true}).fill('Example Owner');
 await page.getByLabel('Authoritative outcome sources',{exact:true}).fill('CRM status owned by Example Owner; payment source unavailable');
 await page.getByRole('button',{name:'Add baseline metric',exact:true}).click();
 await page.getByLabel('Baseline 1 metric',{exact:true}).fill('Human replies');
 await page.getByLabel('Baseline 1 unit',{exact:true}).fill('count');
 await page.getByRole('button',{name:'Save setup',exact:true}).click();
 await expect(page.getByText(/Saved revision 2/)).toBeVisible();
 await page.reload();
 await expect(page.getByLabel('Person 1 email',{exact:true})).toHaveValue('owner@example.invalid');
 await page.getByRole('button',{name:'Create invitation for owner@example.invalid',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('No email was sent');
 await page.getByLabel('What is blocking setup?').fill('Authorize Google access');
 await page.getByLabel('Who can help?').fill('Workspace administrator');
 await page.getByRole('button',{name:'Request assistance',exact:true}).click();
 await expect(page.getByText('Authorize Google access · Workspace administrator')).toBeVisible();
 await page.getByRole('button',{name:/6\. Validate & activate/}).click();
 await expect(page.getByText('Synthetic verification only.',{exact:false}).first()).toBeVisible();
 await page.getByRole('button',{name:'Apply reviewed settings',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Demo operating settings applied');
 await page.getByRole('button',{name:'Resume after readiness checks',exact:true}).click();
 await page.getByRole('button',{name:'Prepare with Account Intelligence',exact:true}).click();
 await page.getByText(/Company positioning profile · draft/).last().click();
 await page.getByRole('button',{name:'Mark output reviewed',exact:true}).click();
 await expect(page.getByText(/Company positioning profile · reviewed/)).toBeVisible();
 await expect(page.getByText('5 of 6 sections complete',{exact:true})).toBeVisible();
 await page.goto(`${origin}/?view=activation&mode=profile&workspace=northstar`);
 await expect(page.getByLabel('Company name',{exact:true})).not.toHaveValue('Example Advisory');
 await page.goto(`${origin}/?view=activation&mode=profile`);
 await page.getByRole('button',{name:/1\. Company & objectives/}).click();
 await expect(page.getByLabel('Company name',{exact:true})).toHaveValue('Example Advisory');
 await expect(page.getByLabel('Offers',{exact:true})).toHaveValue('Advisory\nImplementation');
 await page.screenshot({path:testInfo.outputPath('onboarding-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 for(let i=0;i<6;i++){
  await page.locator('nav[aria-label="Onboarding sections"] button').nth(i).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),`section ${i+1}`).toBe(false);
 }
 await page.locator('nav[aria-label="Onboarding sections"] button').first().click();
 await page.screenshot({path:testInfo.outputPath('onboarding-mobile.png'),fullPage:true});
 expect(errors).toEqual([]);
});
