import {test,expect} from '@playwright/test';
test('studio focuses on one agent, keeps configuration optional, and fits mobile',async({page})=>{
 await page.goto('/?view=team');
 await expect(page.getByRole('heading',{name:'AI agents',exact:true})).toBeVisible();
 await expect(page.locator('.agent-card')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Watch this conversation'})).toBeVisible();
 await page.getByRole('button',{name:'Open Account Intelligence recap'}).click();
 await expect(page).toHaveURL(/view=today/);
 await expect(page.getByRole('region',{name:'Account Intelligence recap'})).toBeVisible();
 await page.getByRole('link',{name:'AI Agents',exact:true}).click();
 await page.getByRole('button',{name:'Workspace limits'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'Close details'}).click();
 await page.getByRole('button',{name:'Build your team',exact:true}).click();
 await expect(page.getByText('Included with every workspace · does not use a slot')).toBeVisible();
 await expect(page.getByRole('heading',{name:'Add beyond the included five.'})).toBeVisible();
 await expect(page.locator('.agent-card')).toHaveCount(33);
 await page.screenshot({path:'artifacts/team-builder-desktop.png'});
 await page.getByRole('button',{name:'Recommend my five',exact:true}).click();
 await expect(page.getByRole('status').filter({hasText:'Recommended team selected below'})).toBeVisible();
 const removed=await page.getByRole('button',{name:/^Remove /}).first().getAttribute('aria-label');
 await page.getByRole('button',{name:/^Remove /}).first().click();
 await page.getByRole('button',{name:'Back to workspace',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Build your team',exact:true}).click();
 await expect(page.getByRole('button',{name:removed!,exact:true})).toHaveCount(0);
 await expect(page.getByRole('button',{name:/^Remove /})).toHaveCount(4);
 await page.screenshot({path:'artifacts/team-builder-mobile.png',fullPage:false});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('Dashboard opens a specialist recap and Results open Pipeline',async({page})=>{
 await page.goto('/?view=today');
 const resume=page.getByRole('button',{name:'Check readiness & resume'});
 if(await resume.isVisible())await resume.click();
 await expect(page.getByRole('heading',{name:'Activity',exact:true})).toHaveCount(0);
 await page.locator('.today-specialist[aria-label="Open Search Growth recap"]').click();
 await expect(page).toHaveURL(/view=today/);
 await expect(page).toHaveURL(/agent=search-growth/);
 await expect(page.getByRole('region',{name:'Search Growth recap'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Prepare first draft'})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Access, limits & history'})).toHaveCount(0);
 await page.getByRole('button',{name:'All specialists'}).click();
 await page.locator('.today-specialist[aria-label="Open Technical SEO recap"]').click();
 await expect(page).toHaveURL(/agent=technical-seo-monitor/);
 await expect(page.getByRole('region',{name:'Technical SEO recap'})).toBeVisible();
 await expect(page.getByText(/does not create trackable leads/i)).toBeVisible();
 await page.getByRole('button',{name:'All specialists'}).click();
 await page.getByRole('button',{name:/New leads/}).click();
 await expect(page.getByRole('heading',{name:'Pipeline',exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
