import { describe, expect, it } from 'vitest';
import type { OutcomeObservation } from '../packages/contracts/src/index';
import { createFixtureState, calculateMetrics, stableId } from '../packages/domain/src/index';

describe('evidence reconciliation and financial boundaries',()=>{
  function observation(value:number|null,at='2026-09-10T16:00:00.000Z'):OutcomeObservation {const state=createFixtureState();return {id:stableId(`outcome:${value}:${at}`),workspaceId:state.workspace.id,opportunityId:state.proposals[0].opportunityId,metric:'verified_bookings',metricVersion:1,stage:'booked',source:'fixture snapshot',periodStart:at,periodEnd:at,value,valueType:'count',currency:null,quality:'fixture',evidence:[state.proposals[0].evidence[0]]};}
  it('counts duplicated observations once and applies a later cancellation snapshot',()=>{const state=createFixtureState();state.outcomes=[observation(1),{...observation(1),id:stableId('duplicate-event')}];expect(calculateMetrics(state).find(m=>m.key==='verified_bookings')?.value).toBe(1);state.outcomes.push(observation(0,'2026-09-11T16:00:00.000Z'));state.asOf='2026-09-11T16:00:00.000Z';expect(calculateMetrics(state).find(m=>m.key==='verified_bookings')?.value).toBe(0);});
  it('keeps conflicting equally-current observations and null counts unavailable',()=>{const state=createFixtureState();state.outcomes=[observation(1),observation(0)];expect(calculateMetrics(state).find(m=>m.key==='verified_bookings')?.value).toBeNull();state.outcomes=[observation(null)];expect(calculateMetrics(state).find(m=>m.key==='verified_bookings')?.value).toBeNull();});
  it('excludes every synthetic proposal, action receipt and outcome from a live read model',()=>{const state=createFixtureState();state.outcomes=[observation(1)];state.workspace.mode='live';const metrics=calculateMetrics(state);expect(metrics.some(m=>m.key.startsWith('pipeline_'))).toBe(false);expect(metrics.find(m=>m.key==='verified_bookings')?.value).toBe(0);expect(metrics.find(m=>m.key==='accepted_actions')?.value).toBe(0);});
  it('selects current proposal versions before counting pipeline and keeps different value kinds separate',()=>{const state=createFixtureState();const proposal=state.proposals[0];state.proposals=[proposal,{...proposal,id:stableId('new-version'),version:2,amountMinor:900000},{...proposal,id:stableId('other-op'),opportunityId:stableId('other-opportunity'),reference:'ONE-TIME',valueKind:'one_time',amountMinor:300000}];const metrics=calculateMetrics(state);expect(metrics.find(m=>m.key==='pipeline_USD_monthly_recurring')?.value).toBe(900000);expect(metrics.find(m=>m.key==='pipeline_USD_one_time')?.value).toBe(300000);state.proposals[1].status='accepted';expect(calculateMetrics(state).some(m=>m.key==='pipeline_USD_monthly_recurring')).toBe(false);});
  it('does not turn missing current amounts into zero or sum cumulative paid snapshots',()=>{const state=createFixtureState();state.proposals=[{...state.proposals[0],amountMinor:null}];expect(calculateMetrics(state).find(m=>m.key==='pipeline_USD_monthly_recurring')?.value).toBeNull();state.outcomes=[{...observation(10000),stage:'paid',metric:'collected_revenue',valueType:'money_minor',currency:'USD'},{...observation(15000,'2026-09-11T16:00:00.000Z'),stage:'paid',metric:'collected_revenue',valueType:'money_minor',currency:'USD'}];state.asOf='2026-09-11T16:00:00.000Z';expect(calculateMetrics(state).find(m=>m.key==='collected_revenue')?.value).toBe(15000);state.outcomes.push({...observation(null,'2026-09-12T16:00:00.000Z'),stage:'paid',metric:'collected_revenue',valueType:'money_minor',currency:'USD'});state.asOf='2026-09-12T16:00:00.000Z';expect(calculateMetrics(state).find(m=>m.key==='collected_revenue')?.value).toBeNull();});
  it('refuses to combine paid observations in different currencies',()=>{const state=createFixtureState();state.outcomes=[{...observation(10000),stage:'paid',metric:'collected_revenue',valueType:'money_minor',currency:'USD'},{...observation(15000),opportunityId:state.proposals[1].opportunityId,stage:'paid',metric:'collected_revenue',valueType:'money_minor',currency:'EUR'}];expect(calculateMetrics(state).find(m=>m.key==='collected_revenue')?.value).toBeNull();});
  it('future evidence cannot change the current as-of metrics',()=>{const state=createFixtureState();state.outcomes=[observation(1,'2026-09-12T16:00:00.000Z')];expect(calculateMetrics(state).find(m=>m.key==='verified_bookings')?.value).toBe(0);});
  it('a missing currency, unknown quality, fractional minor units or an unsafe sum cannot establish financial totals',()=>{const state=createFixtureState();const paid={...observation(10000),stage:'paid' as const,metric:'collected_revenue',valueType:'money_minor' as const,currency:'USD'};state.outcomes=[paid,{...paid,id:stableId('missing-currency'),opportunityId:state.proposals[1].opportunityId,currency:null}];expect(calculateMetrics(state).find(m=>m.key==='collected_revenue')?.value).toBeNull();state.workspace.mode='shadow';state.outcomes=[{...paid,quality:'unknown'}];expect(calculateMetrics(state).find(m=>m.key==='collected_revenue')?.value).toBeNull();state.workspace.mode='fixture';state.outcomes=[{...paid,value:.5},{...paid,id:stableId('fraction-two'),opportunityId:state.proposals[1].opportunityId,value:.5}];expect(calculateMetrics(state).find(m=>m.key==='collected_revenue')?.value).toBeNull();state.outcomes=[{...paid,value:Number.MAX_SAFE_INTEGER},{...paid,id:stableId('unsafe-sum'),opportunityId:state.proposals[1].opportunityId,value:1}];expect(calculateMetrics(state).find(m=>m.key==='collected_revenue')?.value).toBeNull();});
  it('signed value uses latest versions but refuses ambiguous concurrent proposal value kinds',()=>{const state=createFixtureState();const proposal=state.proposals[0];state.proposals=[{...proposal,valueKind:'one_time'},{...proposal,id:stableId('latest-signed-version'),version:2,valueKind:'monthly_recurring'}];state.outcomes=[{...observation(500000),stage:'signed',metric:'signed_value',valueType:'money_minor',currency:'USD'}];expect(calculateMetrics(state).find(m=>m.key==='signed_value')?.value).toBe(500000);state.proposals.push({...proposal,id:stableId('other-current-proposal'),reference:'OTHER-PROPOSAL',valueKind:'one_time'});expect(calculateMetrics(state).find(m=>m.key==='signed_value')?.value).toBeNull();});
});
