import { describe, expect, it } from 'vitest';
import { createFixtureState, executeCommand, snapshot, forecastCases } from '../packages/domain/src/index';
import { Command } from '../packages/contracts/src/index';

describe('explicit responsible-person outcome evidence',()=>{
  it('records attendance separately, keeps it labeled and deduplicates immutable references',async()=>{const state=createFixtureState();const command={type:'record_outcome' as const,proposalId:state.proposals[0].id,stage:'attended' as const,value:1,currency:null,reference:'Owner attendance note, September 10',observedAt:state.asOf};await executeCommand(state,command);expect(state.outcomes[0].quality).toBe('fixture');expect(state.outcomes[0].source).toBe('responsible-person confirmation');expect(snapshot(state).metrics.find(m=>m.key==='attended_meetings')?.value).toBe(1);expect(snapshot(state).metrics.find(m=>m.key==='verified_bookings')?.value).toBe(0);await executeCommand(state,command);expect(state.outcomes).toHaveLength(1);await expect(executeCommand(state,{...command,value:0})).rejects.toThrow(/new correction reference/);});
  it('denies an ordinary member, invalid amounts, future evidence and ambiguous count units',async()=>{const state=createFixtureState();const command={type:'record_outcome' as const,proposalId:state.proposals[0].id,stage:'paid' as const,value:50000,currency:'USD',reference:'Owner payment confirmation',observedAt:state.asOf};await expect(executeCommand(state,command,{...state.context,role:'workspace_member'})).rejects.toThrow(/owner/);expect(Command.safeParse({...command,value:12.34}).success).toBe(false);expect(Command.safeParse({...command,value:-100}).success).toBe(false);await expect(executeCommand(state,{...command,observedAt:'2026-10-10T16:00:00.000Z'})).rejects.toThrow(/future/);await expect(executeCommand(state,{...command,stage:'attended',value:1})).rejects.toThrow(/no currency/);});
  it('retains corrections as cumulative snapshots and reports nonfixture evidence as manual',async()=>{const state=createFixtureState();state.workspace.mode='shadow';state.context.environment='shadow';state.proposals[0].fixture=false;const command={type:'record_outcome' as const,proposalId:state.proposals[0].id,stage:'paid' as const,value:10000,currency:'USD',reference:'Original cumulative payment confirmation',observedAt:'2026-09-09T16:00:00.000Z'};await executeCommand(state,command);await executeCommand(state,{...command,value:8000,reference:'Corrected cumulative value after refund',observedAt:state.asOf});expect(state.outcomes).toHaveLength(2);expect(state.outcomes.every(o=>o.quality==='manually_reported')).toBe(true);const metric=snapshot(state).metrics.find(m=>m.key==='collected_revenue');expect(metric?.value).toBe(8000);expect(metric?.limitation).toContain('manually reported');expect(state.workspace.mode).toBe('shadow');});
  it('a signed confirmation stops pending follow-up and hands authoritative status reconciliation to a human',async()=>{const state=createFixtureState();const proposal=state.proposals[0];await executeCommand(state,{type:'draft',proposalId:proposal.id});await executeCommand(state,{type:'record_outcome',proposalId:proposal.id,stage:'signed',value:500000,currency:'USD',reference:'Signed proposal confirmation by owner',observedAt:state.asOf});expect(state.actions[0].status).toBe('failed');expect(state.contacts[0].humanTakeover).toBe(true);expect(proposal.status).toBe('open');expect(snapshot(state).metrics.find(m=>m.key==='collected_revenue')?.value).toBeNull();});
  it('does not combine signed recurring and one-time values or turn an unknown scenario unit value into zero',async()=>{const state=createFixtureState();state.proposals[1].valueKind='one_time';for(const proposal of state.proposals.slice(0,2))await executeCommand(state,{type:'record_outcome',proposalId:proposal.id,stage:'signed',value:500000,currency:'USD',reference:`Owner confirms ${proposal.reference}`,observedAt:state.asOf});expect(snapshot(state).metrics.find(m=>m.key==='signed_value')?.value).toBeNull();const cases=forecastCases({...state.scenarios[0],valueMinor:null,baselineWins:0,counterfactual:'No action baseline'});expect(cases[1].wins).toBeGreaterThan(0);expect(cases[1].revenueMinor).toBeNull();expect(cases[1].incrementalRoi).toBeNull();});
});
