import { describe, expect, it, vi } from 'vitest';
import { createFixtureState, stableId, preparationIds } from '../packages/domain/src/index';
import { runPreparation, preparationSourceSignature, preparationModelConfig, type PreparationStorePort, type PreparationModelPort, type PreparedRunInput } from '../packages/orchestration/src/model-budget';

function setup(agentId='account-intelligence') {
  const state=createFixtureState('model-preparation-port-tests');
  const company={...state.company,fixture:false,evidence:state.company.evidence.map(e=>({...e,quality:'manually_reported' as const}))};
  const input:PreparedRunInput={workspaceId:state.workspace.id,runId:stableId('preparation-run'),agentId,company};
  const saved=new Map<string,Parameters<PreparationStorePort['save']>[0]>();
  const store:PreparationStorePort={claim:vi.fn(async input=>{const old=saved.get(input.sourceSignature);return old?{status:'unchanged' as const,artifactId:old.artifactId}:{status:'claimed' as const,artifactId:null};}),save:vi.fn(async input=>{saved.set(input.sourceSignature,input);return input.artifactId;}),fail:vi.fn(async()=>{})};
  const model:PreparationModelPort={prepare:vi.fn(async input=>({wording:`Clarify the approved offer\n${input.facts[1].text}`,sourceIds:[input.facts[1].sourceId]}))};
  return {input,store,model,saved};
}
describe('production preparation orchestration through offline ports',()=>{
  it.each(preparationIds.filter(id=>id!=='technical-seo-monitor'))('%s calls the model once and saves only source-cited approved wording with the bounded template',async agentId=>{const {input,store,model,saved}=setup(agentId);const result=await runPreparation(input,store,model);expect(result.status).toBe('preparation_saved');expect(model.prepare).toHaveBeenCalledOnce();const artifact=[...saved.values()][0];expect(artifact.artifact.content).toContain('Model-selected approved wording');expect(artifact.artifact.content).toContain(input.company.evidence[0].id);expect(artifact.artifact.limitation).toBeTruthy();expect(artifact.modelSourceIds).toEqual([input.company.evidence[0].id]);});
  it('technical page checks need no model, and unchanged snapshots do not regenerate on a new day',async()=>{const {input,store,saved}=setup('technical-seo-monitor');await runPreparation(input,store);const previous=[...saved.values()][0];const recaptured={...input,runId:stableId('next-day-run'),company:{...input.company,pages:input.company.pages.map(p=>({...p,capturedAt:'2026-09-12T16:00:00.000Z'}))}};expect(preparationSourceSignature(input.company,input.agentId)).toBe(preparationSourceSignature(recaptured.company,input.agentId));const result=await runPreparation(recaptured,store);expect(result).toEqual({status:'preparation_unchanged',artifactId:previous.artifactId});expect(store.save).toHaveBeenCalledOnce();});
  it('missing model access is a recoverable blocker with no saved generated output',async()=>{const {input,store}=setup();await expect(runPreparation(input,store)).rejects.toThrow('MODEL_ACCESS_MISSING');expect(store.fail).toHaveBeenCalled();expect(store.save).not.toHaveBeenCalled();});
  it('model outage or invented source/copy cannot become an artifact',async()=>{const {input,store,model}=setup();vi.mocked(model.prepare).mockRejectedValueOnce(new Error('synthetic gateway outage'));await expect(runPreparation(input,store,model)).rejects.toThrow('gateway outage');expect(store.save).not.toHaveBeenCalled();vi.mocked(model.prepare).mockResolvedValueOnce({wording:'Clarify the approved offer\nInvented guaranteed 500% growth',sourceIds:[input.company.evidence[0].id]});await expect(runPreparation(input,store,model)).rejects.toThrow('MODEL_WORDING_UNSUPPORTED');vi.mocked(model.prepare).mockResolvedValueOnce({wording:'Clarify the approved offer\nApproved offer',sourceIds:[stableId('different-tenant-source')]});await expect(runPreparation(input,store,model)).rejects.toThrow('MODEL_SOURCE_UNSUPPORTED');});
  it('missing confirmation, fixture context and a denied capacity claim prevent inference',async()=>{const {input,store,model}=setup();await expect(runPreparation({...input,company:{...input.company,confirmed:false}},store,model)).rejects.toThrow('COMPANY_CONFIRMATION_REQUIRED');await expect(runPreparation({...input,company:{...input.company,fixture:true}},store,model)).rejects.toThrow('FIXTURE_DATA');await expect(runPreparation({...input,company:{...input.company,evidence:input.company.evidence.map(item=>({...item,quality:'fixture' as const}))}},store,model)).rejects.toThrow('FIXTURE_DATA');vi.mocked(store.claim).mockRejectedValueOnce(new Error('PREPARATION_DAILY_CAPACITY'));await expect(runPreparation(input,store,model)).rejects.toThrow('DAILY_CAPACITY');expect(model.prepare).not.toHaveBeenCalled();});
  it('requires explicit per-job spending configuration instead of inventing a model budget',()=>{expect(()=>preparationModelConfig({AI_GATEWAY_API_KEY:'SYNTHETIC_KEY',AI_MODEL_ID:'synthetic-model',AI_ALLOWED_PROVIDER:'openai'})).toThrow();expect(()=>preparationModelConfig({AI_GATEWAY_API_KEY:'SYNTHETIC_KEY',AI_MODEL_ID:'synthetic-model',AI_ALLOWED_PROVIDER:'openai',AI_MAX_JOB_COST_MINOR:'0'})).toThrow();expect(preparationModelConfig({AI_GATEWAY_API_KEY:'SYNTHETIC_KEY',AI_MODEL_ID:'synthetic-model',AI_ALLOWED_PROVIDER:'openai',AI_MAX_JOB_COST_MINOR:'5'}).maxCostMinor).toBe(5);});
});
