import { ActionProposal, WorkspaceContext, type ActionReceipt, type EvidenceRef, type ProposalRecord } from '../../contracts/src/index';
import { audit, evidence, nextId, type EngineState, type StandingMandate } from './state';

export class DomainError extends Error { constructor(public code:string, message:string) {super(message);this.name='DomainError';} }
export function authorize(state:EngineState, input:WorkspaceContext=state.context, operation='command') {
  const context=WorkspaceContext.parse(input);
  if(context.workspaceId!==state.workspace.id || context.environment!==state.workspace.mode) throw new DomainError('TENANT_DENIED','Actor and environment do not match the current workspace.');
  if(context.role==='workspace_viewer' || !(context.permittedOperations.includes(operation)||context.permittedOperations.includes('command'))) throw new DomainError('PERMISSION_DENIED','This membership does not permit that operation.');
  if(state.workspace.mode!=='fixture' && context.role==='david_operator' && context.assurance!=='aal2') throw new DomainError('MFA_REQUIRED','Operator changes require MFA assurance.');
  return context;
}
export function assertBound<T extends {workspaceId:string}>(state:EngineState,value:T|undefined,label:string):T {if(!value||value.workspaceId!==state.workspace.id)throw new DomainError('NOT_FOUND',`${label} was not found in this workspace.`);return value;}
export function groundedFollowUpPayload(state:EngineState,proposal:ProposalRecord):ActionProposal['payload'] {const contact=state.contacts.find(c=>c.id===proposal.contactId)!;return {recipient:contact.email,subject:`Following up on ${proposal.reference}`,body:`Hello ${contact.name},\n\nI am following up on proposal ${proposal.reference}. The approved scope is: ${proposal.scopeSummary}\n\nWould a conversation with ${proposal.owner} help you decide on the next step? We can clarify the existing proposal; any change to pricing, scope or terms needs a separate review.\n\nThank you,\n${state.policy.operator}`,proposalVersion:proposal.version};}
export function installationFor(state:EngineState,actionType:ActionProposal['type']) { return state.installations.find(i=>i.agentId===(actionType==='book_appointment'?'appointment-coordinator':'deal-follow-up')); }
const hourAt=(at:string,zone:string)=>Number(new Intl.DateTimeFormat('en-US',{timeZone:zone,hour:'2-digit',hourCycle:'h23'}).format(new Date(at)));
export function eligibility(state:EngineState, proposal:ProposalRecord, actionType:ActionProposal['type']='send_follow_up',actionId?:string):{eligible:boolean;reasons:string[]} {
  const reasons:string[]=[]; const now=Date.parse(state.asOf); const contact=state.contacts.find(c=>c.id===proposal.contactId&&c.workspaceId===state.workspace.id);const installation=installationFor(state,actionType);
  if(proposal.workspaceId!==state.workspace.id)reasons.push('Proposal belongs to another workspace.');
  if(state.workspace.paused)reasons.push('Workspace is paused.');
  if(!contact)reasons.push('The contact identity is missing.');
  if(contact?.suppressed)reasons.push('Contact is suppressed across commercial workflows.');
  if(contact?.humanTakeover)reasons.push('Human takeover is active until explicitly released.');
  if(!contact?.enrolled)reasons.push('Contact is not explicitly enrolled.');
  if(!contact?.owner || !proposal.owner || contact.owner!==proposal.owner)reasons.push('Conversation and proposal ownership need review.');
  if(!installation||!state.activation.selectedTeam.includes(installation.agentId))reasons.push('The required specialist is not selected and installed.');
  if(installation && ['paused','failed','blocked','connection_expired'].includes(installation.status))reasons.push(`The installation is ${installation.status}.`);
  if(proposal.status!=='open')reasons.push(`Proposal status is ${proposal.status}; only current open proposals are eligible.`);
  if(proposal.validUntil&&Date.parse(proposal.validUntil)<=now)reasons.push('Proposal validity has expired.');
  if(now-Date.parse(proposal.sourceVerifiedAt)>state.policy.sourceFreshnessHours*3600000 || Date.parse(proposal.sourceVerifiedAt)>now)reasons.push('Current business status is stale or has an invalid verification time.');
  if(now-Date.parse(proposal.syncedAt)>state.policy.sourceFreshnessHours*3600000)reasons.push('Proposal synchronization is stale.');
  if(!state.policy.confirmed||!state.policy.operator)reasons.push('Operating policy and staffed operator must be confirmed.');
  if(!state.company.confirmed)reasons.push('Company facts require confirmation.');
  const hour=hourAt(state.asOf,state.workspace.timeZone); if(hour<state.policy.workingHours.start||hour>=state.policy.workingHours.end)reasons.push('Outside agreed staffed operating hours.');
  const reply=state.replies[proposal.id];
  if(actionType==='send_follow_up'&&reply)reasons.push(`A ${reply.classification} reply stopped further automated follow-up.`);
  if(actionType==='book_appointment'&&reply?.classification!=='positive')reasons.push('A reviewed positive conversation handoff is required before booking.');
  if(state.outcomes.some(o=>o.opportunityId===proposal.opportunityId&&o.stage==='booked'))reasons.push('A booking already exists; appointment chasing has ended.');
  if(actionType==='send_follow_up'&&contact?.lastContactAt&&now-Date.parse(contact.lastContactAt)<state.policy.spacingHours*3600000)reasons.push('Contact-frequency spacing has not elapsed.');
  if(state.proposals.some(p=>p.workspaceId===state.workspace.id&&p.contactId===proposal.contactId&&p.id!==proposal.id&&p.status==='open'))reasons.push('Several open proposals share this contact; resolve the appropriate proposal and owner.');
  const claim=state.claims[proposal.contactId];if(claim&&claim.actionId!==actionId)reasons.push('Another action owns this contact or awaits reconciliation.');
  if(state.actions.some(a=>a.contactId===proposal.contactId&&a.id!==actionId&&['not_attempted','submitting','uncertain'].includes(a.status)))reasons.push('Another pending action already owns this conversation.');
  if(installation&&state.actions.filter(a=>a.installationId===installation.id&&a.createdAt.slice(0,10)===state.asOf.slice(0,10)&&['submitting','uncertain','provider_accepted','confirmed'].includes(a.status)&&a.id!==actionId).length>=installation.dailyCapacity)reasons.push('Specialist daily action capacity is exhausted.');
  if(state.budget.actions>=state.policy.dailyActionLimit)reasons.push('Daily action capacity is exhausted.');
  const required=actionType==='send_follow_up'?['proposals.current','gmail.send','gmail.reply_read']:['proposals.current','gmail.reply_read','calendar.availability','calendar.book'];
  for(const operation of required)if(!state.connections.some(connection=>connection.workspaceId===state.workspace.id&&connection.operations.includes(operation)&&(connection.health==='healthy'||(state.workspace.mode==='fixture'&&connection.health==='fixture'))&&connection.lastSyncAt&&now-Date.parse(connection.lastSyncAt)<=connection.freshnessSeconds*1000))reasons.push(`Missing or stale bound capability: ${operation}.`);
  if(state.workspace.mode==='shadow')reasons.push('Shadow mode permits internal preparation only.');
  if(state.workspace.mode==='live'){
    const activation=state.policy.liveActivation;
    if(proposal.fixture||state.company.fixture||contact?.email.endsWith('.invalid'))reasons.push('Synthetic fixture data can never enter live execution.');
    if(!activation||Date.parse(activation.expiresAt)<=now||activation.policyVersion!==state.policy.version||activation.sender!==state.policy.sender||!activation.cohortIds.includes(proposal.contactId)||!activation.operator)reasons.push('A current live activation record with this sender, cohort, policy and operator is required.');
  }
  return {eligible:reasons.length===0,reasons};
}
function canonical(value:unknown):string { if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical((value as Record<string,unknown>)[key])}`).join(',')}}`;return JSON.stringify(value); }
export async function actionHash(action:Pick<ActionProposal,'workspaceId'|'installationId'|'contactId'|'proposalId'|'type'|'payload'|'reservedCostMinor'|'expiresAt'>,policyVersion:number) {const digest=await globalThis.crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical({workspaceId:action.workspaceId,installationId:action.installationId,contactId:action.contactId,proposalId:action.proposalId,type:action.type,payload:action.payload,reservedCostMinor:action.reservedCostMinor,expiresAt:action.expiresAt,policyVersion})));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}
export interface ActionProviderPort { refresh?(action:ActionProposal):Promise<void>; submit(action:ActionProposal,options:{idempotencyKey:string}):Promise<{providerId:string;confirmed?:boolean;evidence?:EvidenceRef[]}>; reconcile(action:ActionProposal):Promise<{status:'accepted'|'absent'|'unknown';providerId?:string}> }
export function fixtureProvider(state:EngineState,simulateTimeout=false):ActionProviderPort{return {async submit(action){const result={providerId:`FIXTURE_ONLY_${action.type}_${action.id}`,confirmed:action.type==='book_appointment'};state.fixtureProvider[action.id]=result;if(simulateTimeout)throw new Error('Fixture timeout after acceptance; provider outcome is uncertain.');return result;},async reconcile(action){const result=state.fixtureProvider[action.id];return result?{status:'accepted',providerId:result.providerId}:{status:'unknown'};}};}
function activeMandate(state:EngineState,action:ActionProposal):StandingMandate|undefined {return state.mandates.find(m=>!m.revoked&&Date.parse(m.expiresAt)>Date.parse(state.asOf)&&m.policyVersion===state.policy.version&&m.actionTypes.includes(action.type)&&m.cohortIds.includes(action.contactId)&&m.recipientDomains.includes(action.payload.recipient.split('@')[1])&&m.usedActions<m.maxActions&&m.usedCostMinor+action.reservedCostMinor<=m.maxCostMinor&&state.proposals.find(p=>p.id===action.proposalId)?.scopeSummary===m.approvedScope&&m.templateVersion==='factual-followup.v1'&&action.type==='send_follow_up'&&canonical(action.payload)===canonical(groundedFollowUpPayload(state,state.proposals.find(p=>p.id===action.proposalId)!)));}
async function authority(state:EngineState,action:ActionProposal) {
  const currentHash=await actionHash(action,state.policy.version);
  if(currentHash!==action.payloadHash||state.actionPolicyVersions[action.id]!==state.policy.version) {const previous=state.approvals.find(a=>a.id===action.approvalId);if(previous)previous.status='invalidated';throw new DomainError('APPROVAL_INVALIDATED','Recipient, payload, proposal version or material policy bounds changed. Prepare and approve a new action.');}
  const approval=state.approvals.find(a=>a.id===action.approvalId&&a.workspaceId===state.workspace.id);
  if(approval?.status==='approved'&&approval.payloadHash===currentHash&&Date.parse(approval.expiresAt)>Date.parse(state.asOf))return;
  const mandate=activeMandate(state,action); if(mandate){state.actionMandates[action.id]=mandate.id;return;}
  if(approval&&Date.parse(approval.expiresAt)<=Date.parse(state.asOf))approval.status='expired';
  throw new DomainError('APPROVAL_REQUIRED','This exact action needs current approval or a bounded current standing mandate.');
}
function releaseReservation(state:EngineState,action:ActionProposal,settled:boolean){if(state.claims[action.contactId]?.actionId===action.id)delete state.claims[action.contactId];state.budget.reservedMinor=Math.max(0,state.budget.reservedMinor-action.reservedCostMinor);if(settled){state.budget.settledMinor+=action.reservedCostMinor;state.budget.actions++;const mandate=state.mandates.find(m=>m.id===state.actionMandates[action.id]);if(mandate){mandate.usedActions++;mandate.usedCostMinor+=action.reservedCostMinor;}}}
function appendReceipt(state:EngineState,action:ActionProposal,status:ActionReceipt['status'],providerId:string|null,message:string,proof:EvidenceRef[]=[]) {const receipt:ActionReceipt={id:nextId(state,'receipt'),workspaceId:state.workspace.id,actionId:action.id,status,provider:state.workspace.mode==='fixture'?'fixture':'google',providerId,message,reconciliation:status==='uncertain'?'pending':'not_required',observedAt:state.asOf,evidence:proof};state.receipts.push(receipt);return receipt;}
function recordAccepted(state:EngineState,action:ActionProposal,providerId:string,confirmed=false,proof:EvidenceRef[]=[]){
  action.status=confirmed?'confirmed':'provider_accepted';const synthetic=state.workspace.mode==='fixture';const source=proof.length?proof:[evidence(state,`${synthetic?'Fixture ':'Provider '}receipt ${providerId}`,synthetic?'fixture provider':'google',providerId)];
  appendReceipt(state,action,action.status,providerId,action.type==='send_follow_up'?'Provider accepted the message. Delivery and recipient reading are not verified.':'Calendar booking confirmed; attendance and payment remain unknown.',source);
  const contact=state.contacts.find(c=>c.id===action.contactId)!;contact.lastContactAt=state.asOf;const proposal=state.proposals.find(p=>p.id===action.proposalId)!;const installation=state.installations.find(i=>i.id===action.installationId);if(installation){installation.lastBusinessActionAt=state.asOf;installation.status=state.workspace.paused?'paused':action.type==='send_follow_up'?'waiting_for_reply':'monitoring';}
  state.timeline.push({id:nextId(state,'timeline'),workspaceId:state.workspace.id,opportunityId:proposal.opportunityId,at:state.asOf,kind:action.type,title:action.type==='send_follow_up'?'Follow-up accepted by provider':'Appointment booked',detail:action.type==='send_follow_up'?'No claim of delivery. Waiting for the relevant reply evidence.':`${action.payload.startAt} · ${action.payload.timeZone}. Attendance, contract and payment require separate evidence.`,actor:'david',evidence:source});
  if(action.type==='book_appointment'&&confirmed&&!state.outcomes.some(o=>o.opportunityId===proposal.opportunityId&&o.stage==='booked')){state.outcomes.push({id:nextId(state,'outcome'),workspaceId:state.workspace.id,opportunityId:proposal.opportunityId,metric:'verified_bookings',metricVersion:1,stage:'booked',source:synthetic?'fixture calendar':'google calendar',periodStart:state.asOf,periodEnd:state.asOf,value:1,valueType:'count',currency:null,quality:synthetic?'fixture':'provider_verified',evidence:source});state.appointmentBusy.push({startAt:action.payload.startAt!,endAt:action.payload.endAt!,calendarId:action.payload.calendarId!});}
  releaseReservation(state,action,true);audit(state,'action.accepted',`${action.id}: ${providerId}`);
}
export function checkBooking(state:EngineState,action:ActionProposal){if(action.type!=='book_appointment')return;const {startAt,endAt,timeZone,calendarId}=action.payload;if(!startAt||!endAt||!timeZone||calendarId!==state.policy.calendarId)throw new DomainError('CALENDAR_BINDING','Approved calendar, explicit time and time zone are required.');const start=Date.parse(startAt),end=Date.parse(endAt);if(start<=Date.parse(state.asOf)||end-start!==state.policy.meetingMinutes*60000)throw new DomainError('CALENDAR_TIME','Booking must use a future time and the approved meeting duration.');const localZone=state.workspace.timeZone;const hour=hourAt(startAt,localZone);const endHour=hourAt(endAt,localZone);const endMinute=Number(new Intl.DateTimeFormat('en-US',{timeZone:localZone,minute:'2-digit'}).format(new Date(end)));const day=(at:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:localZone}).format(new Date(at));const weekday=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(new Intl.DateTimeFormat('en-US',{timeZone:localZone,weekday:'short'}).format(new Date(start)));if(!(state.policy.workingDays??[1,2,3,4,5]).includes(weekday)||hour<state.policy.workingHours.start||hour>=state.policy.workingHours.end||endHour>state.policy.workingHours.end||(endHour===state.policy.workingHours.end&&endMinute>0)||day(startAt)!==day(endAt))throw new DomainError('CALENDAR_HOURS','Selected appointment falls outside approved working hours.');if(state.appointmentBusy.some(slot=>slot.calendarId===calendarId&&start<Date.parse(slot.endAt)+(state.policy.bufferMinutes??15)*60000&&end>Date.parse(slot.startAt)-(state.policy.bufferMinutes??15)*60000))throw new DomainError('CALENDAR_CONFLICT','This bound calendar has a conflicting appointment.');if(state.appointmentBusy.filter(slot=>day(slot.startAt)===day(startAt)).length>=state.policy.calendarCapacity)throw new DomainError('CALENDAR_CAPACITY','Daily meeting capacity is exhausted.');}
/** Caller must persist submitting and receipts atomically around provider I/O in hosted operation. The local adapter serializes and persists EngineState per session. */
export async function dispatchAction(state:EngineState,actionId:string,port?:ActionProviderPort,context:WorkspaceContext=state.context) {
  authorize(state,context);const action=assertBound(state,state.actions.find(a=>a.id===actionId),'Action');ActionProposal.parse(action);
  if(['provider_accepted','confirmed'].includes(action.status))return {status:action.status,message:'Action already accepted; no repeat provider write.'};
  if(['submitting','uncertain'].includes(action.status))throw new DomainError('RECONCILIATION_REQUIRED','This action is in flight or uncertain. Reconcile it before considering another action.');
  if(action.status==='failed')throw new DomainError('ACTION_FAILED','This action was stopped. Review and prepare new work after resolving the cause.');
  if(!port&&state.workspace.mode!=='fixture')throw new DomainError('PROVIDER_MISSING','A checked live provider operation is not configured.');
  const provider=port??fixtureProvider(state);const proposal=assertBound(state,state.proposals.find(p=>p.id===action.proposalId),'Proposal');
  if(action.payload.proposalVersion!==proposal.version||action.payload.recipient!==state.contacts.find(c=>c.id===action.contactId)?.email){const approval=state.approvals.find(a=>a.id===action.approvalId);if(approval)approval.status='invalidated';throw new DomainError('SOURCE_CHANGED','Current proposal version or contact channel changed. A new approval is required.');}
  if(Date.parse(action.expiresAt)<=Date.parse(state.asOf))throw new DomainError('ACTION_EXPIRED','Action validity expired.');
  await authority(state,action);
  const allowed=eligibility(state,proposal,action.type,action.id);if(!allowed.eligible)throw new DomainError('NOT_ELIGIBLE',allowed.reasons.join(' '));checkBooking(state,action);
  if(state.claims[action.contactId])throw new DomainError('CONTACT_CLAIMED','This contact has an active claim; no duplicate dispatch.');
  if(state.budget.reservedMinor+state.budget.settledMinor+action.reservedCostMinor>state.policy.dailyBudgetMinor)throw new DomainError('BUDGET_EXHAUSTED','Workspace spending ceiling would be exceeded.');
  state.claims[action.contactId]={actionId:action.id,installationId:action.installationId,fence:++state.sequence,state:'reserved'};state.budget.reservedMinor+=action.reservedCostMinor;
  try {await provider.refresh?.(action);await authority(state,action);const refreshed=assertBound(state,state.proposals.find(p=>p.id===action.proposalId),'Proposal');if(refreshed.version!==action.payload.proposalVersion||state.contacts.find(c=>c.id===action.contactId)?.email!==action.payload.recipient){const approval=state.approvals.find(a=>a.id===action.approvalId);if(approval)approval.status='invalidated';throw new DomainError('SOURCE_CHANGED','Fresh source version or recipient changed; prepare and approve a new action.');}const fresh=eligibility(state,refreshed,action.type,action.id);if(!fresh.eligible)throw new DomainError('FRESH_CHECK_BLOCKED',fresh.reasons.join(' '));checkBooking(state,action);}catch(error){releaseReservation(state,action,false);throw error;}
  action.status='submitting';state.claims[action.contactId].state='submitting';appendReceipt(state,action,'submitting',null,'Provider call is in flight; a pause cannot recall it.');audit(state,'action.submitting',action.id,context);
  try {const result=await provider.submit(structuredClone(action),{idempotencyKey:`david-${action.id}`});recordAccepted(state,action,result.providerId,!!result.confirmed,result.evidence);return {status:action.status,message:action.type==='send_follow_up'?'Provider accepted the follow-up; delivery is not verified.':'Calendar booking recorded. Attendance and financial outcomes remain unknown.'};}
  catch {action.status='uncertain';state.claims[action.contactId].state='uncertain';appendReceipt(state,action,'uncertain',null,'The provider may have accepted this action. Reconcile sent-message/calendar evidence; no blind retry.');audit(state,'action.uncertain',action.id,context);return {status:action.status,message:'Provider outcome is uncertain. The contact remains reserved; reconcile before any new attempt.'};}
}
export async function reconcileAction(state:EngineState,actionId:string,port?:ActionProviderPort,context:WorkspaceContext=state.context){authorize(state,context);const action=assertBound(state,state.actions.find(a=>a.id===actionId),'Action');if(!['uncertain','submitting'].includes(action.status))return 'No uncertain action needs reconciliation.';if(!port&&state.workspace.mode!=='fixture')throw new DomainError('PROVIDER_MISSING','Reconciliation requires the bound provider evidence reader.');const result=await(port??fixtureProvider(state)).reconcile(action);if(result.status==='accepted'&&result.providerId){for(const receipt of state.receipts.filter(r=>r.actionId===action.id&&r.reconciliation==='pending'))receipt.reconciliation='resolved';recordAccepted(state,action,result.providerId,action.type==='book_appointment');return 'Provider evidence found; accepted action retained without another write.';}for(const receipt of state.receipts.filter(r=>r.actionId===action.id&&r.reconciliation==='pending'))receipt.reconciliation='operator_review';return 'Evidence remains inconclusive. Keep contact reserved and ask the assigned operator to review; no automatic resend.';}
