"use client";
import "./onboarding-studio.css";

import { useEffect, useId, useState, type ReactNode } from 'react';
import { OnboardingAnswers } from '@david/contracts';
import { onboardingFor, onboardingReport } from '@david/domain';
import type { ScreenProps } from './app-shell';
import { Button, Badge } from './ui';
import { SourceSetup } from './source-setup';
import { ArrowUpRight, Check, ChevronRight, CircleHelp, Layers3, LockKeyhole, ShieldCheck } from 'lucide-react';

const steps=['Company & objectives','Team & responsibilities','Systems & sources','Operating permissions','People & measurement','Validate & activate'];
const sectionNotes=[
 'Set the business context every specialist will share.',
 'Choose the responsibilities you want this workspace to own.',
 'Connect the accounts and evidence your team can use.',
 'Decide what agents may do, when they work, and who stays in control.',
 'Bring the right people in and define how results will be measured.',
 'Review saved evidence and confirm what is ready for real work.'
];
const lines=(value:string)=>value.split('\n');
function Field({label,value,onChange,multiline=false,type='text',help}:{label:string;value:string;onChange:(value:string)=>void;multiline?:boolean;type?:string;help?:string}) {
 const id=useId();
 return <label className="field">{label}{multiline?<textarea aria-label={label} aria-describedby={help?id:undefined} className="input" rows={3} value={value} onChange={e=>onChange(e.target.value)}/>:<input aria-label={label} aria-describedby={help?id:undefined} className="input" type={type} value={value} onChange={e=>onChange(e.target.value)}/>} {help&&<span id={id} className="help">{help}</span>}</label>;
}
function Select({label,value,onChange,children}:{label:string;value:string;onChange:(value:string)=>void;children:ReactNode}){return <label className="field">{label}<select aria-label={label} className="input" value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>;}
const kinds=['website','proposals','mail','calendar','drive','advertising','social','analytics','calls','payments','commerce','local','rfp','other'] as const;

export function Onboarding(props:ScreenProps){
 const {state,act,busy,navigate}=props;
 const record=onboardingFor(state);
 const [draft,setDraft]=useState(()=>structuredClone(record.answers));
 const [revision,setRevision]=useState(record.revision);
 const [step,setStep]=useState(()=>Math.max(0,onboardingReport(state).complete.findIndex(done=>!done)));
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get('setup');if(value!==null&&/^[0-5]$/.test(value))setStep(Number(value));},[]);
 function changeStep(next:number){setStep(next);const url=new URL(window.location.href);url.searchParams.set('setup',String(next));window.history.replaceState({},'',url.pathname+url.search);}
 const [error,setError]=useState('');
 const [invitationUrl,setInvitationUrl]=useState('');
 const [helpTitle,setHelpTitle]=useState('');
 const [helpOwner,setHelpOwner]=useState('');
 const [readinessView,setReadinessView]=useState<'selected'|'all'>('selected');
 const writable=['workspace_owner','david_operator'].includes(state.context.role);
 const dirty=JSON.stringify(draft)!==JSON.stringify(record.answers);
 const conflict=record.revision!==revision;
 const report=onboardingReport(state);
 const allowance=state.workspace.entitlement??5;
 function company<K extends keyof OnboardingAnswers['company']>(key:K,value:OnboardingAnswers['company'][K]){setDraft(d=>({...d,company:{...d.company,[key]:value}}));}
 function operation<K extends keyof OnboardingAnswers['operations']>(key:K,value:OnboardingAnswers['operations'][K]){setDraft(d=>({...d,operations:{...d.operations,...(!['policyAcknowledged','automationAcknowledged'].includes(key)?{policyAcknowledged:false,automationAcknowledged:false}:{}),[key]:value}}));}
 function system(index:number,key:string,value:string){setDraft(d=>({...d,systems:d.systems.map((s,i)=>i===index?{...s,[key]:value}:s)}));}
 async function save(){
  setError('');const parsed=OnboardingAnswers.safeParse(draft);
  if(!parsed.success){setError(parsed.error.issues.map(i=>`${i.path.join(' → ')}: ${i.message}`).join(' · '));return false;}
  if(conflict){setError('A newer revision is available. Reload its answers before saving. Your unsaved entries remain visible.');return false;}
  const result=await act({type:'save_onboarding',expectedRevision:revision,answers:parsed.data});
  if(!result)return false;
  const next=onboardingFor(result.snapshot);setRevision(next.revision);setDraft(structuredClone(next.answers));return true;
 }
 async function invite(email:string,role:'workspace_owner'|'workspace_member'|'workspace_viewer'){
  if((dirty||record.revision===0)&&!await save())return;
  const result=await act({type:'create_invitation',email,role});setInvitationUrl(result?.invitationUrl??'');
 }
 return <div className="stack onboarding setup-studio">
  <header className="page-heading setup-heading"><div><p className="eyebrow">DAVID / WORKSPACE SETUP</p><h1>Activate your workspace<span aria-hidden="true">.</span></h1><p className="muted">One shared setup. A clear agreement between your people and your agents.</p></div><Button disabled={busy} onClick={async()=>{if(!dirty||await save())navigate('team');}}>Your team <ArrowUpRight size={15}/></Button></header>
  <section className="setup-overview" aria-label="Saved setup overview">
   <div className="setup-overview-title"><span className="setup-kicker">THE FOUNDATION</span><h2>{state.workspace.name}</h2><p>{record.revision?'Your decisions are saved here. Readiness follows the evidence.':'Build the operating context your team will work from.'}</p></div>
   <div className="setup-overview-stats"><div><span className="setup-stat-number">{String(report.complete.filter(Boolean).length).padStart(2,'0')}<small> / 06</small></span><span>{report.complete.filter(Boolean).length} of 6 sections complete</span></div><div><span className="setup-stat-number">{String(report.agents.filter(a=>a.selected).length).padStart(2,'0')}</span><span>Selected responsibilities</span></div></div>
  </section>
  <div className="setup-layout">
   <aside className="setup-sidebar"><span className="setup-kicker">YOUR WORKSPACE BLUEPRINT</span><nav className="onboarding-steps setup-rail" aria-label="Onboarding sections">{steps.map((label,i)=><button key={label} aria-label={`${i+1}. ${label}${report.complete[i]?' — complete':''}`} aria-current={step===i?'step':undefined} onClick={()=>changeStep(i)}><span className="setup-rail-number" aria-hidden="true">{report.complete[i]?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><span><span className="setup-rail-label">{label}</span><small>{report.complete[i]?'Saved requirements complete':'Review requirements'}</small></span><ChevronRight size={14} aria-hidden="true"/></button>)}</nav><p className="setup-sidebar-note"><LockKeyhole size={15}/><span>Progress comes from saved answers and verified checks.</span></p></aside>
   <section className="setup-panel" aria-labelledby="setup-section-title">
    <div className="setup-save-state"><span className="small">{record.revision?`Saved revision ${record.revision} · ${new Date(record.updatedAt).toLocaleString()}`:'Your setup has not been saved yet.'}</span><span className={`setup-draft-state ${dirty?'is-dirty':''}`}>{dirty?'Unsaved changes':'Answers up to date'}</span></div>
    {!writable&&<p className="notice">You can inspect setup. A workspace owner or assigned operator must make changes.</p>}
    {conflict&&<div className="notice notice-warning" role="alert">Setup changed in another session. <Button onClick={()=>{setDraft(structuredClone(record.answers));setRevision(record.revision);setError('');}}>Load latest saved answers</Button><span className="help">Loading replaces your unsaved form entries.</span></div>}
    <header className="setup-section-heading"><span className="setup-section-number" aria-hidden="true">{String(step+1).padStart(2,'0')}</span><div><h2 id="setup-section-title">{steps[step]}</h2><p>{sectionNotes[step]}</p></div></header>
   <fieldset disabled={!writable||busy} className="onboarding-fields">
   {step===0&&<div className="stack">
    <section className="setup-group"><header><span className="setup-kicker">BUSINESS IDENTITY</span><h3>The essentials</h3></header><div className="grid-two"><Field label="Company name" value={draft.company.name} onChange={v=>company('name',v)}/><Field label="Company website" value={draft.company.website} type="url" onChange={v=>company('website',v)}/><Select label="Business model" value={draft.company.businessModel} onChange={v=>company('businessModel',v as typeof draft.company.businessModel)}><option value="b2b_services">B2B services</option><option value="home_services">Home services</option><option value="commerce">Commerce</option></Select><Field label="Time zone" value={draft.company.timeZone} onChange={v=>company('timeZone',v)} help="For example: America/Denver"/></div></section>
    <section className="setup-group"><header><span className="setup-kicker">SHARED CONTEXT</span><h3>Who you serve. What you offer.</h3></header><div className="grid-two"><Field label="Offers" value={draft.company.offers.join('\n')} onChange={v=>company('offers',lines(v))} multiline help="One approved offer per line."/><Field label="Customers you serve" value={draft.company.customers.join('\n')} onChange={v=>company('customers',lines(v))} multiline/><Field label="Business priorities" value={draft.company.priorities.join('\n')} onChange={v=>company('priorities',lines(v))} multiline/><Field label="What would success look like?" value={draft.company.successDefinition} onChange={v=>company('successDefinition',v)} multiline/></div></section><section className="setup-group"><header><span className="setup-kicker">BRAND BOUNDARIES</span><h3>How your team represents you</h3></header><div className="grid-two"><Field label="Brand and communication guidance" value={draft.company.brandGuidance} onChange={v=>company('brandGuidance',v)} multiline/><Field label="Claims and commitments agents must not make" value={draft.company.forbiddenClaims} onChange={v=>company('forbiddenClaims',v)} multiline/></div></section>
    <p className="help">These are owner-supplied facts. In Systems & sources, capture and confirm the supporting evidence before agents use it.</p>
   </div>}
   {step===1&&<div className="stack"><p>{draft.team.length} / {allowance} responsibilities selected. Your allowance is configured by DAVID; selecting an agent does not enable unimplemented work.</p><div className="grid-two setup-responsibilities">{state.catalog.map((agent,index)=>{
    const selected=draft.team.includes(agent.id);const applicable=agent.supportedArchetypes.includes(draft.company.businessModel);const readiness=report.agents.find(a=>a.id===agent.id)!;
    return <article className={`card card-body stack-small setup-responsibility ${selected?'is-selected':''}`} key={agent.id}><span className="setup-kicker">SPECIALIST / {String(index+1).padStart(2,'0')}</span><label className="check-row"><input type="checkbox" checked={selected} disabled={!selected&&draft.team.length>=allowance} onChange={()=>setDraft(d=>({...d,team:selected?d.team.filter(id=>id!==agent.id):[...d.team,agent.id]}))}/><strong>{agent.name}</strong></label><p className="small">{agent.responsibility}</p><div className="flex wrap"><Badge status={agent.releaseStatus}/>{!applicable&&<Badge>Not applicable to this business model</Badge>}</div><p className="help">Sources for this responsibility: {readiness.requiredSystems.join(', ')}.</p><p className="help">Current implemented capability requirements: {agent.requiredCapabilities.join(', ')}.</p></article>;
   })}</div></div>}
   {step===2&&<div className="stack"><p>Record the tools you already use, select the exact sources, and assign someone who can authorize access. A saved source description is not a verified connection.</p>
    {draft.systems.map((source,i)=><article className="card card-body stack setup-source" key={source.id}><header className="setup-card-heading"><span className="setup-kicker">SOURCE / {String(i+1).padStart(2,'0')}</span><h3>{source.tool||'New system'}</h3></header><div className="grid-two"><Select label={`System ${i+1} purpose`} value={source.kind} onChange={v=>system(i,'kind',v)}>{kinds.map(k=><option key={k} value={k}>{k}</option>)}</Select><Field label={`System ${i+1} tool`} value={source.tool} onChange={v=>system(i,'tool',v)}/><Select label={`System ${i+1} availability`} value={source.availability} onChange={v=>system(i,'availability',v)}><option value="available">Available</option><option value="not_available">We do not have this</option><option value="admin_needed">Administrator assistance needed</option></Select><Field label={`System ${i+1} owner`} value={source.owner} onChange={v=>system(i,'owner',v)}/><Field label={`System ${i+1} selected resource`} value={source.resource} onChange={v=>system(i,'resource',v)} help="File URL, mailbox address, calendar or account identifier. Never enter a password or access token."/><Select label={`System ${i+1} connection`} value={source.connectionId} onChange={v=>system(i,'connectionId',v)}><option value="">Not connected</option>{state.connections.filter(c=>c.provider!=='fixture').map(c=><option key={c.id} value={c.id}>{c.identity} · {c.health}</option>)}</Select></div><Field label={`System ${i+1} field mapping and source notes`} value={source.mapping} onChange={v=>system(i,'mapping',v)} multiline/><Button onClick={()=>setDraft(d=>({...d,systems:d.systems.filter((_,j)=>i!==j)}))}>Remove system {i+1}</Button></article>)}
    <Button onClick={()=>setDraft(d=>({...d,systems:[...d.systems,{id:crypto.randomUUID(),kind:'proposals',tool:'',availability:'available',resource:'',owner:'',mapping:'',connectionId:''}]}))} disabled={draft.systems.length>=40}>Add a system</Button>
    <p className="help">Supported live setup: website capture, Google Sheets, Gmail and Calendar. Drive document ingestion and other provider integrations remain engineering requirements; account selection does not claim support.</p>
    <SourceSetup state={state}/><Button onClick={async()=>{if(!dirty||await save())navigate('connections');}}>Open account connections</Button>
   </div>}
   {step===3&&<div className="stack">
    <section className="setup-group"><header><span className="setup-kicker">AUTHORITY</span><h3>Every action has a boundary</h3></header><Select label="External action approvals" value={draft.operations.approvalMode} onChange={v=>{operation('approvalMode',v as typeof draft.operations.approvalMode);operation('automationAcknowledged',false);}}><option value="each_action">Approve every email and booking</option><option value="bounded_follow_up">Authorize bounded automatic follow-up</option></Select>
    {draft.operations.approvalMode==='bounded_follow_up'&&<div className="notice notice-warning stack-small"><p>Bookings still require individual approval. Automatic follow-up uses only the exact factual template below, current proposal scope, and the contacts selected here. Authority expires after seven days and remains subject to provider, budget, reply and pause checks.</p><pre className="onboarding-template">{'Subject: Following up on {reference}\n\nI’m following up on proposal {reference}.\n\n{scopeSummary}\n\nWhat questions can we help answer?'}</pre><label className="check-row"><input type="checkbox" checked={draft.operations.automationAcknowledged} onChange={e=>operation('automationAcknowledged',e.target.checked)}/>I authorize this template and selected contact scope. I understand this changes approval requirements when reviewed settings are applied.</label></div>}</section>
    <section className="setup-group"><header><span className="setup-kicker">CAPACITY & SCHEDULE</span><h3>Your operating limits</h3></header><div className="grid-two"><Field label="Approved sender email" value={draft.operations.sender} type="email" onChange={v=>operation('sender',v)}/><Field label="Booking calendar ID" value={draft.operations.calendarId} onChange={v=>operation('calendarId',v)}/><Field label="Escalation operator email" value={draft.operations.escalationOwner} onChange={v=>operation('escalationOwner',v)} help="For live actions, this must identify an active assigned DAVID operator."/><Field label={`Daily AI budget (${state.workspace.currency} minor units)`} type="number" value={draft.operations.modelDailyBudgetMinor===null?'':String(draft.operations.modelDailyBudgetMinor)} onChange={v=>operation('modelDailyBudgetMinor',v===''?null:Number(v))} help="500 means $5 in USD. Blank means undecided; zero disables model spending. Shared across agents; hosting costs are separate."/>
     {([['dailyCapacity','Daily action / per-agent preparation capacity'],['actionDailyBudgetMinor',`Daily action budget (${state.workspace.currency} minor units)`],['startHour','Working day starts (hour)'],['endHour','Working day ends (hour)'],['meetingMinutes','Meeting duration (minutes)'],['bufferMinutes','Meeting buffer (minutes)']] as const).map(([key,label])=><Field key={key} label={label} type="number" value={String(draft.operations[key])} onChange={v=>operation(key,Number(v))}/>)}</div>
    <Button disabled={busy||dirty||!draft.operations.escalationOwner} onClick={()=>void act({type:'assign_operator',email:draft.operations.escalationOwner})}>Assign registered DAVID operator</Button><p className="help">Save the operator email first. Assignment works only for an existing authorized DAVID operator; it cannot promote a client account.</p>
    <div className="flex wrap" aria-label="Working days">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day,i)=><label className="check-row" key={day}><input type="checkbox" checked={draft.operations.workingDays.includes(i+1)} onChange={e=>operation('workingDays',e.target.checked?[...draft.operations.workingDays,i+1]:draft.operations.workingDays.filter(n=>n!==i+1))}/>{day}</label>)}</div></section>
    <section className="setup-group"><header><span className="setup-kicker">CONTACT PERMISSIONS</span><h3>Who your team can reach</h3></header><Field label="Contact restrictions and exclusion guidance" value={draft.operations.contactRestrictions} onChange={v=>operation('contactRestrictions',v)} multiline help="Review these instructions before choosing the allowed contacts. Free text is not an automatic filter."/>
    <details><summary>Explicitly allowed contacts ({draft.operations.approvedContactIds.length})</summary><p className="help">Only selected, nonsuppressed contacts can be enrolled. Imported data alone never authorizes communication.</p>{state.contacts.map(c=><label className="check-row" key={c.id}><input type="checkbox" disabled={c.suppressed||c.humanTakeover} checked={draft.operations.approvedContactIds.includes(c.id)} onChange={e=>operation('approvedContactIds',e.target.checked?[...draft.operations.approvedContactIds,c.id]:draft.operations.approvedContactIds.filter(id=>id!==c.id))}/>{c.name} · {c.email}{c.suppressed?' · suppressed':''}</label>)}</details>
    <label className="check-row"><input type="checkbox" checked={draft.operations.policyAcknowledged} onChange={e=>operation('policyAcknowledged',e.target.checked)}/>I reviewed these operating limits, contact permissions and escalation responsibilities.</label></section>
   </div>}
   {step===4&&<div className="stack">
    <header className="setup-group-intro"><span className="setup-kicker">HUMAN OVERSIGHT</span><h3>People and responsibilities</h3></header>{draft.people.map((person,i)=><div className="card card-body stack setup-person" key={i}><header className="setup-card-heading"><span className="setup-kicker">PERSON / {String(i+1).padStart(2,'0')}</span><h3>{person.name||'New teammate'}</h3></header><div className="grid-two"><Field label={`Person ${i+1} name`} value={person.name} onChange={v=>setDraft(d=>({...d,people:d.people.map((p,j)=>i===j?{...p,name:v}:p)}))}/><Field label={`Person ${i+1} email`} type="email" value={person.email} onChange={v=>setDraft(d=>({...d,people:d.people.map((p,j)=>i===j?{...p,email:v}:p)}))}/><Select label={`Person ${i+1} responsibility`} value={person.responsibility} onChange={v=>setDraft(d=>({...d,people:d.people.map((p,j)=>i===j?{...p,responsibility:v as typeof p.responsibility}:p)}))}>{['owner','approver','administrator','operator','measurement'].map(r=><option key={r} value={r}>{r}</option>)}</Select><Select label={`Person ${i+1} access`} value={person.role} onChange={v=>setDraft(d=>({...d,people:d.people.map((p,j)=>i===j?{...p,role:v as typeof p.role}:p)}))}><option value="workspace_owner">Owner — can configure and approve</option><option value="workspace_member">Member</option><option value="workspace_viewer">Viewer</option></Select></div><div className="flex wrap"><Button onClick={()=>void invite(person.email,person.role)}>Create invitation for {person.email||'this person'}</Button><Button onClick={()=>setDraft(d=>({...d,people:d.people.filter((_,j)=>i!==j)}))}>Remove person {i+1}</Button></div></div>)}
    <Button onClick={()=>setDraft(d=>({...d,people:[...d.people,{name:'',email:'',responsibility:'approver',role:'workspace_member'}]}))} disabled={draft.people.length>=30}>Add a person</Button>
    {invitationUrl&&<div className="notice stack-small"><p>Share this seven-day invitation privately with the named recipient. No email has been sent.</p><input className="input" aria-label="Invitation link" readOnly value={invitationUrl}/><Button onClick={()=>void navigator.clipboard.writeText(invitationUrl)}>Copy invitation link</Button></div>}
    {record.invitations.map(i=><div className="between wrap" key={i.id}><span className="small">{i.email} · {i.role} · {i.status}</span>{i.status==='pending'&&<Button onClick={()=>void act({type:'revoke_invitation',invitationId:i.id})}>Revoke invitation</Button>}</div>)}
    <p className="help">Approvers need Owner access to approve actions. An invitation does not grant DAVID operator privileges.</p><header className="setup-group-intro"><span className="setup-kicker">MEASURABLE OUTCOMES</span><h3>Measurement and showcase permissions</h3></header><Field label="Measurement owner" value={draft.measurement.owner} onChange={v=>setDraft(d=>({...d,measurement:{...d.measurement,owner:v}}))}/>
    <Field label="Authoritative outcome sources" value={draft.measurement.outcomeSources} onChange={v=>setDraft(d=>({...d,measurement:{...d.measurement,outcomeSources:v}}))} multiline help="Name the system and owner for replies, meetings, signed work and payments you intend to measure. Mark unavailable sources explicitly; these descriptions do not create a provider integration."/>
    {draft.measurement.baseline.map((baseline,i)=><div className="grid-two card card-body" key={i}>{(['metric','unit','source','asOf'] as const).map(key=><Field key={key} label={`Baseline ${i+1} ${key}`} type={key==='asOf'?'date':'text'} value={baseline[key]} onChange={v=>setDraft(d=>({...d,measurement:{...d.measurement,baseline:d.measurement.baseline.map((b,j)=>i===j?{...b,[key]:v}:b)}}))}/>)}<Field label={`Baseline ${i+1} value`} type="number" value={baseline.value===null?'':String(baseline.value)} onChange={v=>setDraft(d=>({...d,measurement:{...d.measurement,baseline:d.measurement.baseline.map((b,j)=>i===j?{...b,value:v===''?null:Number(v)}:b)}}))} help="Leave blank when unknown. Owner-entered baselines are manually reported, not verified outcomes."/><Button onClick={()=>setDraft(d=>({...d,measurement:{...d.measurement,baseline:d.measurement.baseline.filter((_,j)=>i!==j)}}))}>Remove baseline {i+1}</Button></div>)}
    <Button onClick={()=>setDraft(d=>({...d,measurement:{...d.measurement,baseline:[...d.measurement.baseline,{metric:'',unit:'',value:null,source:'',asOf:''}]}}))} disabled={draft.measurement.baseline.length>=20}>Add baseline metric</Button>
    <Select label="Permission to share results" value={draft.measurement.sharing} onChange={v=>setDraft(d=>({...d,measurement:{...d.measurement,sharing:v as typeof d.measurement.sharing}}))}><option value="private">Private — no public sharing</option><option value="aggregate_only">Aggregated results only</option><option value="review_each_release">Require approval for each public release</option></Select><p className="help">This records permission. It does not publish data, prove attribution or change financial totals.</p>
   </div>}
   </fieldset>
   {step===5&&<div className="stack setup-readiness"><p>Readiness is evaluated from saved configuration and retained evidence. Visiting a section or resolving a setup request cannot verify an integration.</p>
    <div className="setup-readiness-actions"><ShieldCheck size={23}/><div className="flex wrap"><Button disabled={!writable||busy||dirty||conflict||!record.revision} onClick={()=>void act({type:'apply_onboarding',expectedRevision:record.revision})}>Apply reviewed settings</Button><Button disabled={!writable||busy||dirty||!state.workspace.paused} onClick={()=>void act({type:'pause',paused:false})}>Resume after readiness checks</Button><Button onClick={()=>navigate('connections')}>Inspect connections</Button></div></div>
    <p className="help">Applying settings configures selected, applicable, implemented agents, capacity, workspace budgets and reviewed policy. It leaves execution paused. Live deployment credentials and verification remain separate.</p>
    <div className="setup-readiness-toolbar"><h3>Agent readiness</h3><div className="setup-view-switch" aria-label="Readiness scope"><button aria-pressed={readinessView==='selected'} onClick={()=>setReadinessView('selected')}>Your team ({report.agents.filter(a=>a.selected).length})</button><button aria-pressed={readinessView==='all'} onClick={()=>setReadinessView('all')}>All specialists ({report.agents.length})</button></div></div>
    {readinessView==='selected'&&!report.agents.some(a=>a.selected)&&<div className="setup-no-team"><Layers3 size={26}/><h3>Start with your team</h3><p>Choose the responsibilities you need, save your selection, then review the requirements here.</p><Button onClick={()=>changeStep(1)}>Choose responsibilities</Button></div>}
    <div className="setup-readiness-grid">{report.agents.filter(agent=>readinessView==='all'||agent.selected).map(agent=><article className="card card-body stack-small setup-readiness-card" key={agent.id}><div className="between wrap"><h3>{agent.name}</h3><div className="flex wrap"><Badge>{agent.selected?'Selected':'Not selected'}</Badge><Badge status={agent.status}/></div></div>{agent.missing.map(reason=><p className="small muted" key={reason}>{reason}</p>)}{agent.selected&&state.catalog.find(c=>c.id===agent.id)?.releaseStatus==='implemented'&&<Button disabled={!writable||busy||dirty||state.workspace.paused} onClick={()=>void act({type:'prepare',agentId:agent.id})}>Prepare with {agent.name}</Button>}{state.artifacts.filter(a=>a.agentId===agent.id).map(artifact=><details key={artifact.id}><summary>{artifact.title} · {artifact.reviewState}</summary><pre className="onboarding-template">{artifact.content}</pre><p className="help">{artifact.limitation}</p><div className="flex wrap"><Button disabled={!writable||busy} onClick={()=>void act({type:'review_artifact',artifactId:artifact.id,decision:'reviewed'})}>Mark output reviewed</Button><Button disabled={!writable||busy} onClick={()=>void act({type:'review_artifact',artifactId:artifact.id,decision:'rejected'})}>Reject output</Button></div></details>)}</article>)}</div>
    <Button onClick={()=>navigate('opportunities')}>Inspect and approve the first proposal workflow</Button>
   </div>}
   {error&&<p className="notice notice-danger" role="alert">{error}</p>}
   <footer className="setup-save-bar"><Button disabled={step===0} onClick={()=>changeStep(step-1)}>Previous section</Button><div className="flex wrap"><Button variant="primary" disabled={!writable||busy||conflict} onClick={()=>void save()}>Save setup</Button><Button disabled={step===5} onClick={()=>changeStep(step+1)}>Next section <ChevronRight size={14}/></Button></div></footer>
   </section>
  </div>
  <section className="setup-assistance"><div className="setup-assistance-intro"><CircleHelp size={22}/><span className="setup-kicker">KEEP SETUP MOVING</span><h2>Ask for setup assistance</h2><p>Assign a missing account, source or configuration decision. This request stays with the workspace.</p></div><div className="stack"><div className="grid-two"><Field label="What is blocking setup?" value={helpTitle} onChange={setHelpTitle}/><Field label="Who can help?" value={helpOwner} onChange={setHelpOwner}/></div><Button disabled={!writable||busy||dirty||!record.revision||!helpTitle||!helpOwner} onClick={async()=>{const result=await act({type:'onboarding_task',expectedRevision:record.revision,taskId:crypto.randomUUID(),title:helpTitle,owner:helpOwner,status:'open',note:''});if(result){setHelpTitle('');setHelpOwner('');}}}>Request assistance</Button><p className="help">Save your answers before creating a request.</p>{record.tasks.map(t=><div className="between wrap" key={t.id}><span>{t.title} · {t.owner}</span><Badge status={t.status}/></div>)}</div></section>
  <details className="setup-history"><summary>Setup revision history ({record.history.length})</summary>{record.history.map(h=><p className="small" key={h.revision}>Revision {h.revision} · {new Date(h.at).toLocaleString()} · {h.actor}: {h.summary}</p>)}</details>
 </div>;
}

export function OnboardingOperator({state,act,busy,navigate}:ScreenProps){
 const record=onboardingFor(state);const report=onboardingReport(state);
 const [allowance,setAllowance]=useState(state.workspace.entitlement??5);
 const [notes,setNotes]=useState<Record<string,string>>({});
 const operator=state.context.role==='david_operator';
 return <section className="setup-operator stack"><header className="setup-operator-heading"><div><span className="setup-kicker">SHARED WORKSPACE / SETUP OPERATIONS</span><h2>Workspace setup queue</h2></div><Button onClick={()=>{const url=new URL(window.location.href);url.searchParams.set('mode','profile');window.history.replaceState({},'',url.pathname+url.search);navigate('activation');}}>Open shared onboarding record <ArrowUpRight size={15}/></Button></header><p className="small">Revision {record.revision} · {report.complete.filter(Boolean).length}/6 verified sections. Customer answers and operator requests share the same workspace record.</p><div className="setup-allowance grid-two"><Field label="Configured agent allowance" type="number" value={String(allowance)} onChange={v=>setAllowance(Number(v))}/><div><Button disabled={!operator||busy} onClick={()=>void act({type:'set_allowance',allowance})}>Update workspace allowance</Button><p className="help">Assigned MFA operators only. Standard workspaces start with five; internal allowances can be expanded up to 32.</p></div></div>
 {record.tasks.length===0&&<div className="setup-queue-empty"><CircleHelp size={24}/><div><h3>No assistance requests yet.</h3><p>Requests from workspace setup appear here with an owner and the revision they relate to.</p></div></div>}{record.tasks.map(task=><div className="card card-body stack-small setup-queue-task" key={task.id}><div className="between wrap"><h3>{task.title}</h3><Badge status={task.status}/></div><p className="small">Owner: {task.owner} · Created for revision {task.revision}{task.revision!==record.revision?' · Review against updated answers':''}</p><Field label={`Resolution note for ${task.title}`} value={notes[task.id]??task.note} onChange={v=>setNotes(n=>({...n,[task.id]:v}))}/><div className="flex wrap">{(['in_progress','resolved'] as const).map(status=><Button key={status} disabled={!operator||busy||(status==='resolved'&&!(notes[task.id]??task.note).trim())} onClick={()=>void act({type:'onboarding_task',expectedRevision:record.revision,taskId:task.id,title:task.title,owner:task.owner,status,note:notes[task.id]??task.note})}>{status==='resolved'?'Resolve request':'Start working'}</Button>)}</div></div>)}
 <details><summary>Selected agent blockers</summary>{report.agents.filter(a=>a.selected).map(a=><p className="small" key={a.id}><strong>{a.name}</strong>: {a.missing.join(' ')||'Verified and ready.'}</p>)}</details><p className="help">Provider app secrets, OAuth registration, email delivery, global model limits and hosted database migrations belong to deployment administration. None are collected in customer forms.</p>
 </section>;
}
