"use client";
import {useEffect,useRef,useState} from 'react';
import type {AppSnapshot,Command,OnboardingAnswers,PreparedSetup} from '@david/contracts';
import {OnboardingAnswers as AnswersSchema} from '@david/contracts';
import {onboardingFor,onboardingReport} from '@david/domain/onboarding';
import {onboardingGoals} from '@david/domain/onboarding-assist';
import {requiredSetupQuestions,setupIsStale,setupSourcesChanged} from '@david/domain/prepared-setup';
import {GuidedOnboarding} from './guided-onboarding';
import {OnboardingDiscovery} from './onboarding-discovery';
import {Button,Badge} from './ui';
import type {ScreenProps} from './app-shell';

const stages=['Start','Accounts','Review setup','First work'];
const sampleBrief='Company: Example Advisory\nServices: revenue operations consulting; implementation workshops\nAudience: B2B service companies\nWe offer sales process assessments.';
function Field({label,value,onChange,multi=false,type='text'}:{label:string;value:string;onChange:(v:string)=>void;multi?:boolean;type?:string}){
 return <label className="field">{label}{multi?<textarea className="input" aria-label={label} rows={3} value={value} onChange={e=>onChange(e.target.value)}/>:<input className="input" aria-label={label} type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;
}
export function PreparedOnboarding(props:ScreenProps){
 const {state,act,busy,navigate}=props;
 const record=onboardingFor(state),setup=state.preparedSetup;
 const alive=useRef(true),latest=useRef(state);latest.current=state;
 const [profile,setProfile]=useState(false),[stage,setStage]=useState(0);
 const [goal,setGoal]=useState<PreparedSetup['goal']>(setup?.goal??onboardingGoals.find(g=>record.answers.company.priorities.includes(g.title))?.id??'demand');
 const [website,setWebsite]=useState(record.answers.company.website||state.onboardingCapture?.pages[0]?.url||'');
 const [draft,setDraft]=useState<OnboardingAnswers>(structuredClone(setup?.acceptedRevision?record.answers:setup?.answers??record.answers));
 const [budgetInput,setBudgetInput]=useState(draft.operations.modelDailyBudgetMinor===null?'':String(draft.operations.modelDailyBudgetMinor/100));
 const [pending,setPending]=useState(false),[message,setMessage]=useState('');
 const [editCompany,setEditCompany]=useState(false),[editPeople,setEditPeople]=useState(false),[editTeam,setEditTeam]=useState(false);
 const [sheetAccess,setSheetAccess]=useState(true),[mailAccess,setMailAccess]=useState(false),[calendarAccess,setCalendarAccess]=useState(false),[broadDiscovery,setBroadDiscovery]=useState(false);
 const demo=state.workspace.mode==='fixture';
 const locked=busy||pending||!['workspace_owner','david_operator'].includes(state.context.role);
 const changedSources=setupSourcesChanged(state);
 const accepted=!!setup?.acceptedRevision&&setup.acceptedRevision===record.revision&&!changedSources;
 const stale=!!setup&&(setup.acceptedRevision?setup.acceptedRevision!==record.revision||changedSources:setupIsStale(state));
 const missing=requiredSetupQuestions(draft);
 const needsExecution=draft.team.some(id=>['deal-follow-up','appointment-coordinator'].includes(id));
 const firstAgent=state.catalog.find(a=>draft.team.includes(a.id)&&a.releaseStatus==='implemented');
 const report=onboardingReport(state);
 const dirty=JSON.stringify(draft)!==JSON.stringify(accepted?record.answers:setup?.answers??record.answers);
 useEffect(()=>{alive.current=true;const q=new URLSearchParams(location.search);setProfile(q.get('mode')==='profile');const step=Number(q.get('step'));if(q.has('step')&&step>=0&&step<=3)setStage(step);else setStage(setup?.acceptedRevision?3:setup?2:0);return()=>{alive.current=false;};},[]);
 function move(next:number){setStage(next);const u=new URL(location.href);u.searchParams.set('step',String(next));u.searchParams.delete('guide');u.searchParams.delete('setup');history.replaceState({},'',u.pathname+u.search);}
 function adopt(snapshot:AppSnapshot){if(!alive.current)return;const answers=snapshot.preparedSetup?.acceptedRevision?onboardingFor(snapshot).answers:snapshot.preparedSetup?.answers??onboardingFor(snapshot).answers;setDraft(structuredClone(answers));setBudgetInput(answers.operations.modelDailyBudgetMinor===null?'':String(answers.operations.modelDailyBudgetMinor/100));}
 async function run(command:Command){if(!alive.current)throw new Error('Workspace changed.');const result=await act(command);if(!result)throw new Error('The change was not saved. Review the message above and try again.');if(!alive.current)throw new Error('Workspace changed.');return result.snapshot;}
 async function request(path:string,body:Record<string,unknown>){if(!alive.current)throw new Error('Workspace changed.');const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId:state.workspace.id,...body})});const result=await r.json();if(!r.ok)throw new Error(result.message??'Setup could not complete.');if(!alive.current)throw new Error('Workspace changed.');return result;}
 async function task(work:()=>Promise<void>){setPending(true);setMessage('');try{await work();}catch(e){if(alive.current)setMessage(e instanceof Error?e.message:'Setup failed. Saved progress is retained.');}finally{if(alive.current)setPending(false);}}
 async function generate(from=latest.current){const result=await run({type:'build_setup',goal,expectedRevision:onboardingFor(from).revision,expectedGeneration:from.preparedSetup?.generation??0});adopt(result);return result;}
 async function begin(){await task(async()=>{let current=latest.current;if(demo){if(!current.onboardingCapture)current=await run({type:'sample_onboarding_capture'});}else if(!current.onboardingCapture||website!==current.onboardingCapture.pages[0]?.url)await request('/api/context/capture',{url:website});await generate(current);move(1);});}
 function company<K extends keyof OnboardingAnswers['company']>(key:K,value:OnboardingAnswers['company'][K]){setDraft(d=>({...d,company:{...d.company,[key]:value},operations:{...d.operations,policyAcknowledged:false}}));}
 function operation<K extends keyof OnboardingAnswers['operations']>(key:K,value:OnboardingAnswers['operations'][K]){setDraft(d=>({...d,operations:{...d.operations,policyAcknowledged:false,[key]:value}}));}
 async function saveProgress(){const parsed=AnswersSchema.parse({...draft,operations:{...draft.operations,policyAcknowledged:false}});const saved=await run({type:'save_onboarding',expectedRevision:record.revision,answers:parsed});await generate(saved);setMessage('Progress saved. Review approval is still required.');}
 async function fullProfile(){await task(async()=>{if(dirty)await saveProgress();const u=new URL(location.href);u.searchParams.set('mode','profile');history.replaceState({},'',u.pathname+u.search);setProfile(true);});}
 async function upload(file:File){await task(async()=>{if(!/\.(txt|md)$/i.test(file.name)||file.size>120000)throw new Error('Choose a text or Markdown brief, maximum 30,000 characters.');const text=await file.text();await run({type:'save_setup_document',name:file.name,text});setMessage('Brief saved. Prepare your setup to review its cited suggestions.');});}
 async function saveSource(source:OnboardingAnswers['systems'][number]){
  if(!alive.current)return false;
  const current=latest.current,answers=structuredClone(onboardingFor(current).answers);
  answers.systems=answers.systems.filter(s=>!(s.kind===source.kind&&s.connectionId===source.connectionId&&s.resource===source.resource));answers.systems.push(source);
  const result=await run({type:'save_onboarding',expectedRevision:onboardingFor(current).revision,answers});latest.current=result;return true;
 }
 async function google(){await task(async()=>{const capabilities=[...(sheetAccess?[broadDiscovery?'sheets_discovery':'sheets']:[]),...(mailAccess?['mail']:[]),...(calendarAccess?['calendar']:[])];const response=await request('/api/google/connect',{capabilities});location.assign(response.url);});}
 async function askAdministrator(){await task(async()=>{const current=latest.current,answers=structuredClone(onboardingFor(current).answers);if(!answers.systems.some(s=>s.availability==='admin_needed'))answers.systems.push({id:crypto.randomUUID(),kind:'other',tool:'Requested account access',availability:'admin_needed',owner:'Workspace administrator',resource:'',mapping:'Requested during setup discovery',connectionId:''});const saved=await run({type:'save_onboarding',expectedRevision:onboardingFor(current).revision,answers});await run({type:'onboarding_task',expectedRevision:onboardingFor(saved).revision,taskId:crypto.randomUUID(),title:'Help authorize the selected source accounts',owner:'Workspace administrator',status:'open',note:'Internal preparation can continue while this source access is resolved.'});setMessage('Administrator assistance requested in the operator queue. No email was sent.');});}
 async function confirmAndApply(current:AppSnapshot,answers:OnboardingAnswers){
  const capture=current.onboardingCapture;if(!capture)throw new Error('Capture the company website before starting source-backed work. Your reviewed setup is saved.');
  if(demo)current=await run({type:'confirm_sample_company',expectedRevision:onboardingFor(current).revision});
  else await request('/api/context/confirm',{contextId:capture.id,sourceHash:capture.sourceHash,companyName:answers.company.name,offers:answers.company.offers,customerTypes:answers.company.customers,locations:[]});
  current=await run({type:'apply_onboarding',expectedRevision:onboardingFor(current).revision});adopt(current);move(3);
 }
 async function approve(){await task(async()=>{if(!setup)throw new Error('Prepare your setup first.');const answers=AnswersSchema.parse(draft);const saved=await run({type:'accept_setup',generation:setup.generation,expectedRevision:record.revision,answers});adopt(saved);await confirmAndApply(saved,answers);});}
 async function firstWork(){await task(async()=>{if(dirty)throw new Error('Review and save your setup changes before starting work.');if(!firstAgent)throw new Error('Choose an implemented preparation in the complete profile.');if(state.workspace.paused)await run({type:'pause',paused:false});await run({type:'prepare',agentId:firstAgent.id});setMessage(demo?'Illustrative preparation saved. Review it below.':'Preparation requested. Refresh to see its retained output or runtime blocker.');});}
 if(profile)return <GuidedOnboarding {...props}/>;
 return <div className="stack prepared-onboarding">
  <div className="page-heading between wrap"><div><p className="eyebrow">Workspace setup</p><h1>Start with what you have.</h1><p className="muted">We prepare the setup. You review the decisions.</p></div><Button disabled={locked} onClick={()=>void fullProfile()}>Review complete profile</Button></div>
  <nav className="onboarding-steps" aria-label="Prepared setup stages">{stages.map((label,i)=><Button key={label} disabled={pending||(i>0&&!setup)} variant={stage===i?'primary':''} aria-current={stage===i?'step':undefined} onClick={()=>move(i)}>{i+1}. {label}</Button>)}</nav>
  <p className="small muted">{setup?`Saved proposal ${setup.generation} · ${accepted?'Setup reviewed':stale?'Source or answer changes need a fresh proposal':'Awaiting your review'}`:'Your accepted workspace answers remain available in the complete profile.'}{dirty?' · Unsaved edits':''}</p>
  {message&&<p role="status" className="notice">{message}</p>}
  <fieldset disabled={locked} className="onboarding-fields stack">
  {stage===0&&<section className="card card-body stack">
   <p className="eyebrow">01 / A starting point</p><h2>What should DAVID help you accomplish?</h2>
   {demo?<p className="notice">Browser demo: we’ll use Example Advisory and synthetic records. No real website or account is read.</p>:<Field label="Company website" type="url" value={website} onChange={setWebsite}/>}
   <div className="guided-goals">{onboardingGoals.map(g=><label className="card card-body check-row" key={g.id}><input type="radio" name="setup-objective" checked={goal===g.id} onChange={()=>setGoal(g.id)}/><span><strong>{g.title}</strong><span className="help">{g.success}</span></span></label>)}</div>
   <details><summary>Add an existing company brief (optional)</summary><div className="stack-small">
    <p>Use a service overview or company brief you already have. DAVID extracts explicit company, offer and customer statements with source excerpts. It does not take operating instructions from the document.</p>
    {demo?<Button onClick={()=>void task(async()=>{await run({type:'save_setup_document',name:'Example Advisory company brief.md',text:sampleBrief});setMessage('Illustrative brief saved for discovery.');})}>Use a sample company brief</Button>:<label className="field">Select a text or Markdown brief<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>}
    {(state.setupDocuments??[]).map(doc=><div className="between wrap" key={doc.id}><span>{doc.name} · {doc.fixture?'Sample':'Selected by your workspace'}</span><Button onClick={()=>void task(async()=>{await run({type:'remove_setup_document',documentId:doc.id});})}>Remove {doc.name}</Button></div>)}
   </div></details>
   <Button variant="primary" disabled={!demo&&!website} onClick={()=>void begin()}>{pending?'Preparing your setup…':demo?'Prepare a sample setup':'Prepare my setup'}</Button>
   <p className="help">We’ll read up to three public pages and your selected briefs. You can correct every proposed fact. Nothing is sent, published or booked.</p>
  </section>}
  {stage===1&&<section className="stack">
   <div className="card card-body stack"><p className="eyebrow">02 / Account access</p><h2>Connect what’s useful now.</h2><p>Your website is enough for {firstAgent?.name??'an implemented preparation'}. {needsExecution?'Proposal follow-up and booking still need account access and separate verification.':'Other accounts can wait until a selected capability needs them.'}</p>
    {demo?<p className="notice">Real OAuth and source discovery require the operational deployment. The optional sample below demonstrates mapping review.</p>:<details open={needsExecution}><summary>Connect Google and select the resources to read</summary><div className="stack-small"><label className="check-row"><input type="checkbox" checked={sheetAccess} onChange={e=>setSheetAccess(e.target.checked)}/>Proposal spreadsheets</label>{sheetAccess&&<label className="check-row"><input type="checkbox" checked={broadDiscovery} onChange={e=>setBroadDiscovery(e.target.checked)}/>Allow read-only spreadsheet discovery</label>}<label className="check-row"><input type="checkbox" checked={mailAccess} onChange={e=>setMailAccess(e.target.checked)}/>Gmail sender and reply account</label><label className="check-row"><input type="checkbox" checked={calendarAccess} onChange={e=>setCalendarAccess(e.target.checked)}/>Owned booking calendar</label><p className="help">Default Sheets access is file-specific and includes editing rights; DAVID only reads. Optional discovery permits Drive metadata and reads of all spreadsheets; DAVID lists names and reads only selected files. Gmail grants mailbox-wide read and send scopes; DAVID processes enrolled threads and requires separate sending approval. Google shows the exact scopes.</p><Button disabled={!sheetAccess&&!mailAccess&&!calendarAccess} onClick={()=>void google()}>Authorize selected Google access</Button></div></details>}
    <div className="flex wrap"><Button variant="primary" onClick={()=>void task(async()=>{await generate();move(2);})}>Review my prepared setup</Button><Button onClick={()=>void askAdministrator()}>Ask an administrator for access</Button></div>
   </div>
   <details><summary>{demo?'Try sample spreadsheet discovery':'Review connected resources and suggested mappings'}</summary><OnboardingDiscovery key={state.workspace.id} state={state} onSave={saveSource}/></details>
  </section>}
  {stage===2&&setup&&<section className="stack">
   {stale&&<div role="alert" className="notice notice-warning">Sources or saved answers changed. <Button onClick={()=>void task(async()=>{await generate();})}>Refresh the prepared setup</Button> Your saved answers will be retained.</div>}
   <div className="card card-body stack"><p className="eyebrow">03 / Review the proposal</p><h2>Here’s the setup we prepared.</h2><p>Review what we found. Open a section only to correct it; unanswered facts appear as questions.</p>
    <div className="setup-summary-grid">
     <article className="setup-summary"><div className="between wrap"><h3>Company</h3><Button onClick={()=>setEditCompany(!editCompany)}>{editCompany?'Close company editor':'Edit company details'}</Button></div><strong>{draft.company.name||'Company name needed'}</strong><p>{draft.company.offers.join(' · ')||'What do you offer?'}</p><p className="muted">For {draft.company.customers.join(' · ')||'which customers?'}</p>
      {(editCompany||missing.some(m=>m.startsWith('company.')))&&<div className="stack-small"><Field label="Company name" value={draft.company.name} onChange={v=>company('name',v)}/><Field label="Offers" multi value={draft.company.offers.join('\n')} onChange={v=>company('offers',v.split('\n').filter(Boolean))}/><Field label="Customers" multi value={draft.company.customers.join('\n')} onChange={v=>company('customers',v.split('\n').filter(Boolean))}/><label className="field">Business model<select className="input" value={draft.company.businessModel} onChange={e=>company('businessModel',e.target.value as typeof draft.company.businessModel)}><option value="b2b_services">B2B services</option><option value="home_services">Home services</option><option value="commerce">Commerce</option></select></label></div>}
     </article>
     <article className="setup-summary"><div className="between wrap"><h3>Your team</h3><Button onClick={()=>setEditTeam(!editTeam)}>Adjust team</Button></div><p>{draft.company.priorities.join(' · ')}</p>{draft.team.map(id=>{const agent=state.catalog.find(a=>a.id===id);return <p className="small" key={id}><strong>{agent?.name}</strong> · {agent?.releaseStatus==='implemented'?'Internal preparation':agent?.releaseStatus==='pilot'?'Requires account verification':'Requires implementation'}</p>;})}
      {editTeam&&<div className="stack-small">{state.catalog.filter(a=>a.supportedArchetypes.includes(draft.company.businessModel)).map(a=><label className="check-row" key={a.id}><input type="checkbox" checked={draft.team.includes(a.id)} disabled={!draft.team.includes(a.id)&&draft.team.length>=(state.workspace.entitlement??5)} onChange={e=>setDraft(d=>({...d,team:e.target.checked?[...d.team,a.id]:d.team.filter(id=>id!==a.id),operations:{...d.operations,policyAcknowledged:false}}))}/>{a.name}</label>)}</div>}
      <p className="help">An unfinished integration won’t stop an available preparation. Review its exact capability before enabling work.</p>
     </article>
    </div>
    {setup.conflicts.length>0&&<details className="notice"><summary>{setup.conflicts.length} source comparison(s) to review</summary>{setup.conflicts.map((c,i)=><p key={i}>{c}</p>)}</details>}
    <details><summary>Sources behind this setup ({setup.citations.length})</summary>{setup.citations.map((c,i)=><div className="guided-citation" key={i}><strong>{c.field.replaceAll('.',' / ')} · {c.value}</strong><blockquote>{c.quote}</blockquote><p className="help">{c.basis} · {/^https:\/\//.test(c.source)?<a href={c.source} target="_blank" rel="noreferrer">{c.source}</a>:c.source}</p></div>)}</details>
   </div>
   <div className="card card-body stack"><h3>Measurement sources</h3><p>{draft.measurement.baseline.filter(b=>b.value!==null).length} recorded baseline(s) · {draft.measurement.baseline.filter(b=>b.value===null).length} unknown. Missing measurements need a source before impact can be reported; internal drafts can start without them.</p><details><summary>Review baseline values and sources</summary>{draft.measurement.baseline.map((b,i)=><div className="setup-baseline" key={i}><strong>{b.metric}</strong><span>{b.value===null?'Unknown':`${b.value} ${b.unit}`} {b.asOf?`· ${b.asOf}`:''}</span><p className="help">{b.source}</p></div>)}<p className="help">No revenue, uplift or complete-company coverage is inferred. Measurement sources stay editable in the complete profile.</p></details></div>
   <div className="card card-body stack"><h3>Decisions that need your approval</h3><div className="between wrap"><p>Approver: <strong>{draft.people.find(p=>p.responsibility==='approver')?.email||'Choose an approver'}</strong><br/>Escalations: <strong>{draft.operations.escalationOwner||'Choose a responsible person'}</strong></p><Button onClick={()=>setEditPeople(!editPeople)}>Change responsibilities</Button></div>
    {(editPeople||missing.includes('people.approver')||!draft.operations.escalationOwner)&&<div className="grid-two"><Field label="Approver email" type="email" value={draft.people.find(p=>p.responsibility==='approver')?.email??''} onChange={v=>setDraft(d=>({...d,people:[...d.people.filter(p=>p.responsibility!=='approver'),{name:v,email:v,responsibility:'approver',role:'workspace_owner'}],operations:{...d.operations,policyAcknowledged:false}}))}/><Field label="Escalation owner email" type="email" value={draft.operations.escalationOwner} onChange={v=>operation('escalationOwner',v)}/></div>}
    <label className="field">Daily AI spending limit ({state.workspace.currency})<input aria-label="Daily AI spending limit" className="input" type="text" inputMode="decimal" value={budgetInput} onChange={e=>{const value=e.target.value;setBudgetInput(value);operation('modelDailyBudgetMinor',value.trim()!==''&&/^\d*(?:\.\d{0,2})?$/.test(value)&&Number.isFinite(Number(value))?Math.round(Number(value)*100):null);}}/></label><p className="help">Choose the amount explicitly. 0 disables model spending. Source discovery itself makes no model calls.</p>
    <details><summary>Review limits and privacy</summary><div className="grid-two"><Field label="Daily capacity per agent" type="number" value={String(draft.operations.dailyCapacity)} onChange={v=>operation('dailyCapacity',Number(v))}/><Field label="Working time zone" value={draft.company.timeZone} onChange={v=>company('timeZone',v)}/></div><p>{draft.operations.workingDays.map(d=>['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][d-1]).join(', ')} · {draft.operations.startHour}:00–{draft.operations.endHour}:00 · {draft.company.timeZone}</p><p>{draft.operations.approvedContactIds.length} approved contacts. Sharing: {draft.measurement.sharing}. External action budget: {(draft.operations.actionDailyBudgetMinor/100).toFixed(2)} {state.workspace.currency} per day.</p><p>{draft.operations.contactRestrictions||'No additional contact restrictions entered. Only explicitly selected contacts can be enrolled.'}</p><Button onClick={()=>void fullProfile()}>Edit advanced operating permissions</Button></details>
    <p className="small">Proposed capacity: {draft.operations.dailyCapacity} per agent/day. {draft.operations.approvalMode==='each_action'?'Every external action requires approval.':'Previously authorized bounded follow-up remains selected; review its exact scope in the complete profile.'} Responsibility suggestions do not invite people or grant account access.</p>
    <label className="check-row"><input type="checkbox" checked={draft.operations.policyAcknowledged} onChange={e=>setDraft(d=>({...d,operations:{...d.operations,policyAcknowledged:e.target.checked}}))}/>I reviewed the company facts, team, responsibilities and operating limits shown here.</label>
    <div className="flex wrap"><Button variant="primary" disabled={stale||accepted||missing.length>0||!draft.team.length} onClick={()=>void approve()}>Approve this setup</Button><Button disabled={!dirty} onClick={()=>void task(saveProgress)}>{accepted?'Save changes for review':'Save progress for later'}</Button></div>
    {accepted&&(record.appliedRevision===record.revision?<Button onClick={()=>move(3)}>Continue to first work</Button>:<><p className="notice">Your setup was saved. Continue its source confirmation and settings check before first work.</p><Button onClick={()=>void task(async()=>{await confirmAndApply(latest.current,record.answers);})}>Continue setup checks</Button></>)}
   </div>
  </section>}
  {stage===3&&<section className="stack"><div className="card card-body stack"><p className="eyebrow">04 / First useful work</p><h2>Start with a preparation you can review.</h2><p>{firstAgent?`${firstAgent.name} can use your confirmed company sources to prepare internal work.`:'Select an implemented preparation in the complete profile.'} Account-dependent agents keep their own blockers.</p><Button variant="primary" disabled={dirty||!accepted||!state.activation.confirmedFacts||record.appliedRevision!==record.revision||!firstAgent} onClick={()=>void firstWork()}>{firstAgent?`Start ${firstAgent.name}`:'Choose a preparation'}</Button><p className="help">This resumes the workspace through its existing readiness checks and requests this preparation. Your reviewed policy and spending limits still apply. It does not approve an external action.</p>{!accepted&&<Button onClick={()=>move(2)}>Review your setup first</Button>}</div>
   {report.agents.filter(a=>a.selected).map(a=><article className="card card-body stack-small" key={a.id}><div className="between wrap"><h3>{a.name}</h3><Badge status={a.status}/></div><details><summary>Requirements and current evidence</summary>{a.missing.map((m,i)=><p className="small" key={i}>{m}</p>)}</details>{state.artifacts.filter(o=>o.agentId===a.id).map(o=><details key={o.id} open={o.reviewState==='draft'}><summary>{o.title} · {o.reviewState}</summary><pre className="onboarding-template">{o.content}</pre><p className="help">{o.limitation}</p><div className="flex wrap"><Button onClick={()=>void task(async()=>{await run({type:'review_artifact',artifactId:o.id,decision:'reviewed'});})}>Accept this output</Button><Button onClick={()=>void task(async()=>{await run({type:'review_artifact',artifactId:o.id,decision:'rejected'});})}>Reject this output</Button></div></details>)}</article>)}<Button onClick={()=>navigate('connections')}>Inspect account checks</Button>
  </section>}
  </fieldset>
  {stage>0&&<Button disabled={locked} onClick={()=>move(stage-1)}>Previous</Button>}
 </div>;
}
