import {NextResponse} from 'next/server';
import {z} from 'zod';
import {authClient} from '../../../../lib/auth';
import {apiError,HttpError} from '../../../../lib/http';
import {environment} from '../../../../../../packages/orchestration/src/environment';
import {runtimeDatabase} from '../../../../../../packages/orchestration/src/database';
import {exchangeGoogleCode,hashOAuthState} from '../../../../../../packages/connectors/src/index';
export const runtime='nodejs';
export async function GET(request:Request){try{const env=environment();if(!env.GOOGLE_CLIENT_ID||!env.GOOGLE_CLIENT_SECRET||!env.GOOGLE_REDIRECT_URI)throw new HttpError(503,'GOOGLE_UNCONFIGURED','The Google OAuth application is not configured.');const url=new URL(request.url);if(url.origin+url.pathname!==env.GOOGLE_REDIRECT_URI)throw new HttpError(403,'CALLBACK_URI_DENIED','OAuth redirect does not match the configured callback.');const state=z.string().min(32).max(256).parse(url.searchParams.get('state'));const code=z.string().min(1).max(4096).parse(url.searchParams.get('code'));const stateHash=hashOAuthState(state);const client=await authClient();const {data,error}=await client.rpc('consume_google_oauth',{p_state_hash:stateHash,p_redirect_uri:env.GOOGLE_REDIRECT_URI});if(error||!data?.[0])throw new HttpError(403,'OAUTH_STATE_DENIED','This connection request expired, was already used or belongs to a different actor.');const tokens=await exchangeGoogleCode({code,verifier:data[0].verifier,redirectUri:env.GOOGLE_REDIRECT_URI,clientId:env.GOOGLE_CLIENT_ID,clientSecret:env.GOOGLE_CLIENT_SECRET});await runtimeDatabase().finishOAuth({stateHash,...tokens});const response=NextResponse.redirect(new URL(`/?view=activation&step=1&workspace=${encodeURIComponent(data[0].workspace_id)}`,env.APP_ORIGIN));response.headers.set('Cache-Control','private, no-store');return response;}catch(error){return apiError(error);}}
