export function register() {
  const forbidden = ['WORKER_DATABASE_URL','DISPATCHER_DATABASE_URL','DAVID_OAUTH_DATABASE_URL','MIGRATION_DATABASE_URL','TEST_DATABASE_URL','PRIVACY_DATABASE_URL','PRIVACY_STORAGE_SERVICE_KEY','SUPABASE_SERVICE_ROLE_KEY','SUPABASE_SECRET_KEY','NEXT_PUBLIC_SUPABASE_URL','NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY','GOOGLE_CLIENT_SECRET','GOOGLE_REFRESH_TOKEN','CRON_SECRET','AI_GATEWAY_API_KEY','INSTANTLY_API_KEY','INSTANTLY_WEBHOOK_SECRET'];
  if (forbidden.some(key => process.env[key])) throw new Error('PUBLIC_DEMO_CREDENTIALS_DENIED: Remove operational credentials from the separate demo deployment.');
}
